import { fe1024, fe1024img } from "../helper";

export default () => [
  {
    title: "2D_Breakout",
    name: "2D_Breakout",
    url: fe1024("2D_Breakout"),
    cover: fe1024img("2D_Breakout.webp"),
  },
  {
    title: "2D_Fighting_game",
    name: "2D_Fighting_game",
    url: fe1024("2D_Fighting_game"),
    cover: fe1024img("2D_Fighting_game.webp"),
  },
  {
    title: "3d_Box_Game",
    name: "3d_Box_Game",
    url: fe1024("3d_Box_Game"),
    cover: fe1024img("3d_Box_Game.webp"),
  },
  {
    title: "3D_Car_Racing_Game",
    name: "3D_Car_Racing_Game",
    url: fe1024("3D_Car_Racing_Game"),
    cover: fe1024img("3D_Car_Racing_Game.png"),
  },
  {
    title: "3d_Snake",
    name: "3d_Snake",
    url: fe1024("3d_Snake"),
    cover: fe1024img("3d_Snake.png"),
  },
  {
    title: "8_Puzzle",
    name: "8_Puzzle",
    url: fe1024("8_Puzzle"),
    cover: fe1024img("8_Puzzle.png"),
  },
  {
    title: "16_Puzzle",
    name: "16_Puzzle",
    url: fe1024("16_Puzzle"),
    cover: fe1024img("16_Puzzle.png"),
  },
  {
    title: "1024_Moves",
    name: "1024_Moves",
    url: fe1024("1024_Moves"),
    cover: fe1024img("1024_Moves.jpg"),
  },
  {
    title: "2048_win",
    name: "2048_win",
    url: fe1024("2048_win"),
    cover: fe1024img("2048_win.png"),
  },
  {
    title: "Achluophobia",
    name: "Achluophobia",
    url: fe1024("Achluophobia"),
    cover: fe1024img("Achluophobia.webp"),
  },
  {
    title: "AI_CHESS_Game",
    name: "AI_CHESS_Game",
    url: fe1024("AI_CHESS_Game"),
    cover: fe1024img("AI_CHESS_Game.jpg"),
  },
  {
    title: "Adventure_Game",
    name: "Adventure_Game",
    url: fe1024("Adventure_Game"),
    cover: fe1024img("Adventure_Game.webp"),
  },
  {
    title: "Aero_Acrobat",
    name: "Aero_Acrobat",
    url: fe1024("Aero_Acrobat"),
    cover: fe1024img("Aero_Acrobat.webp"),
  },
  {
    title: "Aim_Training",
    name: "Aim_Training",
    url: fe1024("Aim_Training"),
    cover: fe1024img("Aim_Training.webp"),
  },
  {
    title: "AirBalloon",
    name: "AirBalloon",
    url: fe1024("AirBalloon"),
    cover: fe1024img("AirBalloon.webp"),
  },
  {
    title: "Airhocky_game",
    name: "Airhocky_game",
    url: fe1024("Airhocky_game"),
    cover: fe1024img("Airhocky_game.png"),
  },
  {
    title: "Alien_Invasion",
    name: "Alien_Invasion",
    url: fe1024("Alien_Invasion"),
    cover: fe1024img("Alien_Invasion.png"),
  },
  // {
  //   title: "Alien_Language_Translator",
  //   name: "Alien_Language_Translator",
  //   url: fe1024("Alien_Language_Translator"),
  //   cover: fe1024img("Alien_Language_Translator.png"),
  // },
  {
    title: "Alien_Shooters",
    name: "Alien_Shooters",
    url: fe1024("Alien_Shooters"),
    cover: fe1024img("Alien_Shooters.webp"),
  },
  {
    title: "Align_4_Game",
    name: "Align_4_Game",
    url: fe1024("Align_4_Game"),
    cover: fe1024img("Align_4_Game.png"),
  },
  {
    title: "Alphabet",
    name: "Alphabet",
    url: fe1024("Alphabet"),
    cover: fe1024img("Alphabet.webp"),
  },
  {
    title: "Alphabet-and-Vowels",
    name: "Alphabet-and-Vowels",
    url: fe1024("Alphabet-and-Vowels"),
    cover: fe1024img("Alphabet-and-Vowels.jpeg"),
  },
  {
    title: "Alphabet_Learning_Game",
    name: "Alphabet_Learning_Game",
    url: fe1024("Alphabet_Learning_Game"),
    cover: fe1024img("Alphabet_Learning_Game.webp"),
  },
  {
    title: "Am_I_the_number",
    name: "Am_I_the_number",
    url: fe1024("Am_I_the_number"),
    cover: fe1024img("Am_I_the_number.png"),
  },
  {
    title: "Among_Us_Game",
    name: "Among_Us_Game",
    url: fe1024("Among_Us_Game"),
    cover: fe1024img("Among_Us_Game.webp"),
  },
  {
    title: "Anagram-Word-Game",
    name: "Anagram-Word-Game",
    url: fe1024("Anagram-Word-Game"),
    cover: fe1024img("Anagram-Word-Game.jpeg"),
  },
  {
    title: "Anagram_Checker_Game",
    name: "Anagram_Checker_Game",
    url: fe1024("Anagram_Checker_Game"),
    cover: fe1024img("Anagram_Checker_Game.png"),
  },
  // {
  //   title: "Angry_Bird",
  //   name: "Angry_Bird",
  //   url: fe1024("Angry_Bird"),
  //   cover: fe1024img("Angry_Bird.png"),
  // },
  {
    title: "Angry_Boars",
    name: "Angry_Boars",
    url: fe1024("Angry_Boars"),
    cover: fe1024img("Angry_Boars.webp"),
  },
  {
    title: "Animal_Match_Game",
    name: "Animal_Match_Game",
    url: fe1024("Animal_Match_Game"),
    cover: fe1024img("Animal_Match_Game.webp"),
  },
  {
    title: "Animal_Name_Guessing",
    name: "Animal_Name_Guessing",
    url: fe1024("Animal_Name_Guessing"),
    cover: fe1024img("Animal_Name_Guessing.png"),
  },
  {
    title: "Anime_Clicker",
    name: "Anime_Clicker",
    url: fe1024("Anime_Clicker"),
    cover: fe1024img("Anime_Clicker.png"),
  },
  {
    title: "Ant_Smasher",
    name: "Ant_Smasher",
    url: fe1024("Ant_Smasher"),
    cover: fe1024img("Ant_Smasher.png"),
  },
  {
    title: "AquaSort_Game",
    name: "AquaSort_Game",
    url: fe1024("AquaSort_Game"),
    cover: fe1024img("AquaSort_Game.png"),
  },
  {
    title: "Arcade_Game",
    name: "Arcade_Game",
    url: fe1024("Arcade_Game"),
    cover: fe1024img("Arcade_Game.webp"),
  },
  {
    title: "Archery",
    name: "Archery",
    url: fe1024("Archery"),
    cover: fe1024img("Archery.png"),
  },
  {
    title: "Arkanoid_Game",
    name: "Arkanoid_Game",
    url: fe1024("Arkanoid_Game"),
    cover: fe1024img("Arkanoid_Game.png"),
  },
  {
    title: "ArmorAlley",
    name: "ArmorAlley",
    url: fe1024("ArmorAlley"),
    cover: fe1024img("ArmorAlley.webp"),
  },
  {
    title: "Asteroids_3D",
    name: "Asteroids_3D",
    url: fe1024("Asteroids_3D"),
    cover: fe1024img("Asteroids_3D.png"),
  },
  {
    title: "Astronaunt_runner",
    name: "Astronaunt_runner",
    url: fe1024("Astronaunt_runner"),
    cover: fe1024img("Astronaunt_runner.png"),
  },
  {
    title: "Atari_breakout",
    name: "Atari_breakout",
    url: fe1024("Atari_breakout"),
    cover: fe1024img("Atari_breakout.webp"),
  },
  {
    title: "Atlas_Game",
    name: "Atlas_Game",
    url: fe1024("Atlas_Game"),
    cover: fe1024img("Atlas_Game.png"),
  },
  {
    title: "Audio_Wordle",
    name: "Audio_Wordle",
    url: fe1024("Audio_Wordle"),
    cover: fe1024img("Audio_Wordle.png"),
  },
  {
    title: "Avax_Gods",
    name: "Avax_Gods",
    url: fe1024("Avax_Gods"),
    cover: fe1024img("Avax_Gods.webp"),
  },
  {
    title: "Avoider_Game",
    name: "Avoider_Game",
    url: fe1024("Avoider_Game"),
    cover: fe1024img("Avoider_Game.webp"),
  },
  {
    title: "Back_To_Space",
    name: "Back_To_Space",
    url: fe1024("Back_To_Space"),
    cover: fe1024img("Back_To_Space.jpg"),
  },
  {
    title: "Bad_Depot",
    name: "Bad_Depot",
    url: fe1024("Bad_Depot"),
    cover: fe1024img("Bad_Depot.webp"),
  },
  {
    title: "Bad_Luck_Brian",
    name: "Bad_Luck_Brian",
    url: fe1024("Bad_Luck_Brian"),
    cover: fe1024img("Bad_Luck_Brian.webp"),
  },
  {
    title: "Ball-And-Paddle-Game",
    name: "Ball-And-Paddle-Game",
    url: fe1024("Ball-And-Paddle-Game"),
    cover: fe1024img("Ball-And-Paddle-Game.png"),
  },
  {
    title: "Ball_Fall_Game",
    name: "Ball_Fall_Game",
    url: fe1024("Ball_Fall_Game"),
    cover: fe1024img("Ball_Fall_Game.webp"),
  },
  {
    title: "Ball_Shooting_Game",
    name: "Ball_Shooting_Game",
    url: fe1024("Ball_Shooting_Game"),
    cover: fe1024img("Ball_Shooting_Game.png"),
  },
  {
    title: "Ball_and_glass",
    name: "Ball_and_glass",
    url: fe1024("Ball_and_glass"),
    cover: fe1024img("Ball_and_glass.png"),
  },
  {
    title: "Ball_in_Maze",
    name: "Ball_in_Maze",
    url: fe1024("Ball_in_Maze"),
    cover: fe1024img("Ball_in_Maze.png"),
  },
  {
    title: "Ballarena",
    name: "Ballarena",
    url: fe1024("Ballarena"),
    cover: fe1024img("Ballarena.webp"),
  },
  {
    title: "Balloon_Buster",
    name: "Balloon_Buster",
    url: fe1024("Balloon_Buster"),
    cover: fe1024img("Balloon_Buster.jpeg"),
  },
  {
    title: "Balloon_Defense_Game",
    name: "Balloon_Defense_Game",
    url: fe1024("Balloon_Defense_Game"),
    cover: fe1024img("Balloon_Defense_Game.png"),
  },
  {
    title: "Balloon_Popup",
    name: "Balloon_Popup",
    url: fe1024("Balloon_Popup"),
    cover: fe1024img("Balloon_Popup.png"),
  },
  {
    title: "Baseball",
    name: "Baseball",
    url: fe1024("Baseball"),
    cover: fe1024img("Baseball.png"),
  },
  {
    title: "Basketball",
    name: "Basketball",
    url: fe1024("Basketball"),
    cover: fe1024img("Basketball.webp"),
  },
  {
    title: "Bash_mole",
    name: "Bash_mole",
    url: fe1024("Bash_mole"),
    cover: fe1024img("Bash_mole.png"),
  },
  {
    title: "Battleship",
    name: "Battleship",
    url: fe1024("Battleship"),
    cover: fe1024img("Battleship.png"),
  },
  {
    title: "Bear_Hunter_Ninja",
    name: "Bear_Hunter_Ninja",
    url: fe1024("Bear_Hunter_Ninja"),
    cover: fe1024img("Bear_Hunter_Ninja.png"),
  },
  {
    title: "Beat_a_mole",
    name: "Beat_a_mole",
    url: fe1024("Beat_a_mole"),
    cover: fe1024img("Beat_a_mole.png"),
  },
  {
    title: "Belt_Black",
    name: "Belt_Black",
    url: fe1024("Belt_Black"),
    cover: fe1024img("Belt_Black.png"),
  },
  {
    title: "Beyblade",
    name: "Beyblade",
    url: fe1024("Beyblade"),
    cover: fe1024img("Beyblade.png"),
  },
  {
    title: "Beyonder",
    name: "Beyonder",
    url: fe1024("Beyonder"),
    cover: fe1024img("Beyonder.jpg"),
  },
  {
    title: "Bingo_Game",
    name: "Bingo_Game",
    url: fe1024("Bingo_Game"),
    cover: fe1024img("Bingo_Game.webp"),
  },
  {
    title: "Bird_game",
    name: "Bird_game",
    url: fe1024("Bird_game"),
    cover: fe1024img("Bird_game.webp"),
  },
  {
    title: "Bit_Maze_Platformer_Maze",
    name: "Bit_Maze_Platformer_Maze",
    url: fe1024("Bit_Maze_Platformer_Maze"),
    cover: fe1024img("Bit_Maze_Platformer_Maze.webp"),
  },
  {
    title: "Black_Jack",
    name: "Black_Jack",
    url: fe1024("Black_Jack"),
    cover: fe1024img("Black_Jack.webp"),
  },
  {
    title: "Black_jackk",
    name: "Black_jackk",
    url: fe1024("Black_jackk"),
    cover: fe1024img("Black_jackk.png"),
  },
  {
    title: "Blanks_Detective",
    name: "Blanks_Detective",
    url: fe1024("Blanks_Detective"),
    cover: fe1024img("Blanks_Detective.webp"),
  },
  {
    title: "Blast_Zone",
    name: "Blast_Zone",
    url: fe1024("Blast_Zone"),
    cover: fe1024img("Blast_Zone.webp"),
  },
  {
    title: "Blink_Beat",
    name: "Blink_Beat",
    url: fe1024("Blink_Beat"),
    cover: fe1024img("Blink_Beat.png"),
  },
  {
    title: "Block_Game",
    name: "Block_Game",
    url: fe1024("Block_Game"),
    cover: fe1024img("Block_Game.jpg"),
  },
  {
    title: "Block.io",
    name: "Block.io",
    url: fe1024("Block.io"),
    cover: fe1024img("Block.io.webp"),
  },
  {
    title: "Block_Building",
    name: "Block_Building",
    url: fe1024("Block_Building"),
    cover: fe1024img("Block_Building.png"),
  },
  {
    title: "Block_Buster",
    name: "Block_Buster",
    url: fe1024("Block_Buster"),
    cover: fe1024img("Block_Buster.png"),
  },
  {
    title: "Block_Dodger",
    name: "Block_Dodger",
    url: fe1024("Block_Dodger"),
    cover: fe1024img("Block_Dodger.png"),
  },
  {
    title: "Block_Ninja",
    name: "Block_Ninja",
    url: fe1024("Block_Ninja"),
    cover: fe1024img("Block_Ninja.png"),
  },
  {
    title: "Block_Vault",
    name: "Block_Vault",
    url: fe1024("Block_Vault"),
    cover: fe1024img("Block_Vault.png"),
  },
  {
    title: "Bomb_Throw_Game",
    name: "Bomb_Throw_Game",
    url: fe1024("Bomb_Throw_Game"),
    cover: fe1024img("Bomb_Throw_Game.png"),
  },
  {
    title: "Boom_Blast",
    name: "Boom_Blast",
    url: fe1024("Boom_Blast"),
    cover: fe1024img("Boom_Blast.png"),
  },
  {
    title: "Bottle_Flip",
    name: "Bottle_Flip",
    url: fe1024("Bottle_Flip"),
    cover: fe1024img("Bottle_Flip.png"),
  },
  {
    title: "Bounce_Ball",
    name: "Bounce_Ball",
    url: fe1024("Bounce_Ball"),
    cover: fe1024img("Bounce_Ball.png"),
  },
  {
    title: "Bouncing_Ball_Game",
    name: "Bouncing_Ball_Game",
    url: fe1024("Bouncing_Ball_Game"),
    cover: fe1024img("Bouncing_Ball_Game.png"),
  },
  {
    title: "Bow_And_Arrow",
    name: "Bow_And_Arrow",
    url: fe1024("Bow_And_Arrow"),
    cover: fe1024img("Bow_And_Arrow.png"),
  },
  {
    title: "Bow_Arrow",
    name: "Bow_Arrow",
    url: fe1024("Bow_Arrow"),
    cover: fe1024img("Bow_Arrow.webp"),
  },
  {
    title: "Box_In_Air_Game",
    name: "Box_In_Air_Game",
    url: fe1024("Box_In_Air_Game"),
    cover: fe1024img("Box_In_Air_Game.png"),
  },
  {
    title: "Box_Merge",
    name: "Box_Merge",
    url: fe1024("Box_Merge"),
    cover: fe1024img("Box_Merge.png"),
  },
  {
    title: "Brain_Burst_Game",
    name: "Brain_Burst_Game",
    url: fe1024("Brain_Burst_Game"),
    cover: fe1024img("Brain_Burst_Game.png"),
  },
  {
    title: "Brain_Color_Mastermind",
    name: "Brain_Color_Mastermind",
    url: fe1024("Brain_Color_Mastermind"),
    cover: fe1024img("Brain_Color_Mastermind.webp"),
  },
  {
    title: "Brain_Game",
    name: "Brain_Game",
    url: fe1024("Brain_Game"),
    cover: fe1024img("Brain_Game.png"),
  },
  {
    title: "Brain_card_game",
    name: "Brain_card_game",
    url: fe1024("Brain_card_game"),
    cover: fe1024img("Brain_card_game.png"),
  },
  {
    title: "Breakout",
    name: "Breakout",
    url: fe1024("Breakout"),
    cover: fe1024img("Breakout.webp"),
  },
  {
    title: "Brick_Buster",
    name: "Brick_Buster",
    url: fe1024("Brick_Buster"),
    cover: fe1024img("Brick_Buster.png"),
  },
  {
    title: "Brick_Breaker",
    name: "Brick_Breaker",
    url: fe1024("Brick_Breaker"),
    cover: fe1024img("Brick_Breaker.webp"),
  },
  {
    title: "Brick_and_Ball",
    name: "Brick_and_Ball",
    url: fe1024("Brick_and_Ball"),
    cover: fe1024img("Brick_and_Ball.png"),
  },
  // {
  //   title: "Bubble'z_Popper",
  //   name: "Bubble'z_Popper",
  //   url: fe1024("Bubble'z_Popper"),
  //   cover: fe1024img("Bubble'z_Popper.png"),
  // },
  {
    title: "Bubble_Blast_Game",
    name: "Bubble_Blast_Game",
    url: fe1024("Bubble_Blast_Game"),
    cover: fe1024img("Bubble_Blast_Game.webp"),
  },
  {
    title: "Bubble_Shooter",
    name: "Bubble_Shooter",
    url: fe1024("Bubble_Shooter"),
    cover: fe1024img("Bubble_Shooter.png"),
  },
  {
    title: "Building_Block_Game",
    name: "Building_Block_Game",
    url: fe1024("Building_Block_Game"),
    cover: fe1024img("Building_Block_Game.png"),
  },
  {
    title: "Bulls_And_Cows_New",
    name: "Bulls_And_Cows_New",
    url: fe1024("Bulls_And_Cows_New"),
    cover: fe1024img("Bulls_And_Cows_New.png"),
  },
  {
    title: "Bulls_and_Cows",
    name: "Bulls_and_Cows",
    url: fe1024("Bulls_and_Cows"),
    cover: fe1024img("Bulls_and_Cows.png"),
  },
  {
    title: "Bulls_eye",
    name: "Bulls_eye",
    url: fe1024("Bulls_eye"),
    cover: fe1024img("Bulls_eye.png"),
  },
  {
    title: "Bunny_is_Lost",
    name: "Bunny_is_Lost",
    url: fe1024("Bunny_is_Lost"),
    cover: fe1024img("Bunny_is_Lost.png"),
  },
  {
    title: "CHESS",
    name: "CHESS",
    url: fe1024("CHESS"),
    cover: fe1024img("CHESS.webp"),
  },
  {
    title: "CSS_Crossword",
    name: "CSS_Crossword",
    url: fe1024("CSS_Crossword"),
    cover: fe1024img("CSS_Crossword.png"),
  },
  {
    title: "CSS_Select",
    name: "CSS_Select",
    url: fe1024("CSS_Select"),
    cover: fe1024img("CSS_Select.png"),
  },
  {
    title: "Cable_Maze",
    name: "Cable_Maze",
    url: fe1024("Cable_Maze"),
    cover: fe1024img("Cable_Maze.jpg"),
  },
  {
    title: "Caesar_Cipher",
    name: "Caesar_Cipher",
    url: fe1024("Caesar_Cipher"),
    cover: fe1024img("Caesar_Cipher.webp"),
  },
  // {
  //   title: "Call_Of_Duty",
  //   name: "Call_Of_Duty",
  //   url: fe1024("Call_Of_Duty"),
  //   cover: fe1024img("Call_Of_Duty.png"),
  // },
  {
    title: "Candy_Crush",
    name: "Candy_Crush",
    url: fe1024("Candy_Crush"),
    cover: fe1024img("Candy_Crush.webp"),
  },
  {
    title: "Candy_Crush_Saga",
    name: "Candy_Crush_Saga",
    url: fe1024("Candy_Crush_Saga"),
    cover: fe1024img("Candy_Crush_Saga.png"),
  },
  {
    title: "Candy_Match_Saga",
    name: "Candy_Match_Saga",
    url: fe1024("Candy_Match_Saga"),
    cover: fe1024img("Candy_Match_Saga.jpg"),
  },
  {
    title: "Canon_Defense",
    name: "Canon_Defense",
    url: fe1024("Canon_Defense"),
    cover: fe1024img("Canon_Defense.webp"),
  },
  {
    title: "CareTaker",
    name: "CareTaker",
    url: fe1024("CareTaker"),
    cover: fe1024img("CareTaker.webp"),
  },
  {
    title: "Carnival_game",
    name: "Carnival_game",
    url: fe1024("Carnival_game"),
    cover: fe1024img("Carnival_game.webp"),
  },
  {
    title: "Carrom",
    name: "Carrom",
    url: fe1024("Carrom"),
    cover: fe1024img("Carrom.jpg"),
  },
  {
    title: "Cartoon_Character_Guessing_Game",
    name: "Cartoon_Character_Guessing_Game",
    url: fe1024("Cartoon_Character_Guessing_Game"),
    cover: fe1024img("Cartoon_Character_Guessing_Game.png"),
  },
  {
    title: "Cast_and_Catch",
    name: "Cast_and_Catch",
    url: fe1024("Cast_and_Catch"),
    cover: fe1024img("Cast_and_Catch.webp"),
  },
  {
    title: "Cat_Goric",
    name: "Cat_Goric",
    url: fe1024("Cat_Goric"),
    cover: fe1024img("Cat_Goric.jpg"),
  },
  {
    title: "Catch_Him",
    name: "Catch_Him",
    url: fe1024("Catch_Him"),
    cover: fe1024img("Catch_Him.png"),
  },
  {
    title: "Catch-the-falling-Stars",
    name: "Catch-the-falling-Stars",
    url: fe1024("Catch-the-falling-Stars"),
    cover: fe1024img("Catch-the-falling-Stars.png"),
  },
  {
    title: "CatchTheBall",
    name: "CatchTheBall",
    url: fe1024("CatchTheBall"),
    cover: fe1024img("CatchTheBall.png"),
  },
  {
    title: "Catch_Craze",
    name: "Catch_Craze",
    url: fe1024("Catch_Craze"),
    cover: fe1024img("Catch_Craze.png"),
  },
  {
    title: "Catch_Stars",
    name: "Catch_Stars",
    url: fe1024("Catch_Stars"),
    cover: fe1024img("Catch_Stars.jpeg"),
  },
  {
    title: "Catch_The_Ball",
    name: "Catch_The_Ball",
    url: fe1024("Catch_The_Ball"),
    cover: fe1024img("Catch_The_Ball.png"),
  },
  {
    title: "Catch_The_Circle",
    name: "Catch_The_Circle",
    url: fe1024("Catch_The_Circle"),
    cover: fe1024img("Catch_The_Circle.png"),
  },
  {
    title: "Catch_The_Falling_Object",
    name: "Catch_The_Falling_Object",
    url: fe1024("Catch_The_Falling_Object"),
    cover: fe1024img("Catch_The_Falling_Object.png"),
  },
  {
    title: "Catch_The_Objects",
    name: "Catch_The_Objects",
    url: fe1024("Catch_The_Objects"),
    cover: fe1024img("Catch_The_Objects.png"),
  },
  {
    title: "Catch_me_game",
    name: "Catch_me_game",
    url: fe1024("Catch_me_game"),
    cover: fe1024img("Catch_me_game.webp"),
  },
  {
    title: "Catch_the_Bunny",
    name: "Catch_the_Bunny",
    url: fe1024("Catch_the_Bunny"),
    cover: fe1024img("Catch_the_Bunny.webp"),
  },
  {
    title: "Charon_Jr",
    name: "Charon_Jr",
    url: fe1024("Charon_Jr"),
    cover: fe1024img("Charon_Jr.jpg"),
  },
  {
    title: "Checkers",
    name: "Checkers",
    url: fe1024("Checkers"),
    cover: fe1024img("Checkers.webp"),
  },
  {
    title: "Chess.com",
    name: "Chess.com",
    url: fe1024("Chess.com"),
    cover: fe1024img("Chess.com.jpg"),
  },
  {
    title: "Chess_Game",
    name: "Chess_Game",
    url: fe1024("Chess_Game"),
    cover: fe1024img("Chess_Game.jpg"),
  },
  {
    title: "Chess_Game_computer",
    name: "Chess_Game_computer",
    url: fe1024("Chess_Game_computer"),
    cover: fe1024img("Chess_Game_computer.png"),
  },
  {
    title: "Chicken_cannon",
    name: "Chicken_cannon",
    url: fe1024("Chicken_cannon"),
    cover: fe1024img("Chicken_cannon.png"),
  },
  {
    title: "Chopsticks",
    name: "Chopsticks",
    url: fe1024("Chopsticks"),
    cover: fe1024img("Chopsticks.png"),
  },
  {
    title: "Chrome_Dino_Game",
    name: "Chrome_Dino_Game",
    url: fe1024("Chrome_Dino_Game"),
    cover: fe1024img("Chrome_Dino_Game.png"),
  },
  {
    title: "Chrome_Dinosaur_Game",
    name: "Chrome_Dinosaur_Game",
    url: fe1024("Chrome_Dinosaur_Game"),
    cover: fe1024img("Chrome_Dinosaur_Game.webp"),
  },
  {
    title: "Circuit_Craze",
    name: "Circuit_Craze",
    url: fe1024("Circuit_Craze"),
    cover: fe1024img("Circuit_Craze.png"),
  },
  {
    title: "Circus_Charly",
    name: "Circus_Charly",
    url: fe1024("Circus_Charly"),
    cover: fe1024img("Circus_Charly.jpeg"),
  },
  {
    title: "City_Builder_Game",
    name: "City_Builder_Game",
    url: fe1024("City_Builder_Game"),
    cover: fe1024img("City_Builder_Game.png"),
  },
  {
    title: "CodePen_Simulator",
    name: "CodePen_Simulator",
    url: fe1024("CodePen_Simulator"),
    cover: fe1024img("CodePen_Simulator.webp"),
  },
  {
    title: "Code_Cracker",
    name: "Code_Cracker",
    url: fe1024("Code_Cracker"),
    cover: fe1024img("Code_Cracker.png"),
  },
  {
    title: "Color_The_Page",
    name: "Color_The_Page",
    url: fe1024("Color_The_Page"),
    cover: fe1024img("Color_The_Page.png"),
  },
  {
    title: "Color-Blink-Challenge",
    name: "Color-Blink-Challenge",
    url: fe1024("Color-Blink-Challenge"),
    cover: fe1024img("Color-Blink-Challenge.png"),
  },
  {
    title: "Color_Blast",
    name: "Color_Blast",
    url: fe1024("Color_Blast"),
    cover: fe1024img("Color_Blast.png"),
  },
  {
    title: "Color_Crush_Game",
    name: "Color_Crush_Game",
    url: fe1024("Color_Crush_Game"),
    cover: fe1024img("Color_Crush_Game.png"),
  },
  {
    title: "Color_Shifter",
    name: "Color_Shifter",
    url: fe1024("Color_Shifter"),
    cover: fe1024img("Color_Shifter.png"),
  },
  {
    title: "Color_Swap",
    name: "Color_Swap",
    url: fe1024("Color_Swap"),
    cover: fe1024img("Color_Swap.png"),
  },
  {
    title: "Color_Turner",
    name: "Color_Turner",
    url: fe1024("Color_Turner"),
    cover: fe1024img("Color_Turner.png"),
  },
  {
    title: "Color_switcher",
    name: "Color_switcher",
    url: fe1024("Color_switcher"),
    cover: fe1024img("Color_switcher.webp"),
  },
  {
    title: "Coloron",
    name: "Coloron",
    url: fe1024("Coloron"),
    cover: fe1024img("Coloron.png"),
  },
  {
    title: "Colour_Generator_Game",
    name: "Colour_Generator_Game",
    url: fe1024("Colour_Generator_Game"),
    cover: fe1024img("Colour_Generator_Game.png"),
  },
  {
    title: "Colour_Guessing_Game",
    name: "Colour_Guessing_Game",
    url: fe1024("Colour_Guessing_Game"),
    cover: fe1024img("Colour_Guessing_Game.webp"),
  },
  {
    title: "Computer_Bingo",
    name: "Computer_Bingo",
    url: fe1024("Computer_Bingo"),
    cover: fe1024img("Computer_Bingo.png"),
  },
  {
    title: "Connect4",
    name: "Connect4",
    url: fe1024("Connect4"),
    cover: fe1024img("Connect4.webp"),
  },
  {
    title: "Connect_Four",
    name: "Connect_Four",
    url: fe1024("Connect_Four"),
    cover: fe1024img("Connect_Four.png"),
  },
  {
    title: "Conqueror_Quest",
    name: "Conqueror_Quest",
    url: fe1024("Conqueror_Quest"),
    cover: fe1024img("Conqueror_Quest.png"),
  },
  {
    title: "Cooking_Challenge_Game",
    name: "Cooking_Challenge_Game",
    url: fe1024("Cooking_Challenge_Game"),
    cover: fe1024img("Cooking_Challenge_Game.png"),
  },
  {
    title: "CopyCat",
    name: "CopyCat",
    url: fe1024("CopyCat"),
    cover: fe1024img("CopyCat.png"),
  },
  {
    title: "Corona_Fighter",
    name: "Corona_Fighter",
    url: fe1024("Corona_Fighter"),
    cover: fe1024img("Corona_Fighter.png"),
  },
  {
    title: "Corona_Shooter",
    name: "Corona_Shooter",
    url: fe1024("Corona_Shooter"),
    cover: fe1024img("Corona_Shooter.webp"),
  },
  {
    title: "Cosmic_Blast",
    name: "Cosmic_Blast",
    url: fe1024("Cosmic_Blast"),
    cover: fe1024img("Cosmic_Blast.png"),
  },
  {
    title: "Cosmic_Coin_Collector",
    name: "Cosmic_Coin_Collector",
    url: fe1024("Cosmic_Coin_Collector"),
    cover: fe1024img("Cosmic_Coin_Collector.webp"),
  },
  {
    title: "Country_Guesser_Game",
    name: "Country_Guesser_Game",
    url: fe1024("Country_Guesser_Game"),
    cover: fe1024img("Country_Guesser_Game.webp"),
  },
  // {
  //   title: "CowBull",
  //   name: "CowBull",
  //   url: fe1024("CowBull"),
  //   cover: fe1024img("CowBull.png"),
  // },
  {
    title: "Crack_The_Code",
    name: "Crack_The_Code",
    url: fe1024("Crack_The_Code"),
    cover: fe1024img("Crack_The_Code.webp"),
  },
  {
    title: "Cross_Road_Game",
    name: "Cross_Road_Game",
    url: fe1024("Cross_Road_Game"),
    cover: fe1024img("Cross_Road_Game.png"),
  },
  {
    title: "Cross_The_River_Game",
    name: "Cross_The_River_Game",
    url: fe1024("Cross_The_River_Game"),
    cover: fe1024img("Cross_The_River_Game.png"),
  },
  {
    title: "Cross_The_Road",
    name: "Cross_The_Road",
    url: fe1024("Cross_The_Road"),
    cover: fe1024img("Cross_The_Road.webp"),
  },
  {
    title: "Crossword_Game",
    name: "Crossword_Game",
    url: fe1024("Crossword_Game"),
    cover: fe1024img("Crossword_Game.webp"),
  },
  {
    title: "Crossword_Puzzle",
    name: "Crossword_Puzzle",
    url: fe1024("Crossword_Puzzle"),
    cover: fe1024img("Crossword_Puzzle.webp"),
  },
  {
    title: "Crossy_Road",
    name: "Crossy_Road",
    url: fe1024("Crossy_Road"),
    cover: fe1024img("Crossy_Road.png"),
  },
  {
    title: "Crystals_Collector",
    name: "Crystals_Collector",
    url: fe1024("Crystals_Collector"),
    cover: fe1024img("Crystals_Collector.webp"),
  },
  {
    title: "Currency_Converter",
    name: "Currency_Converter",
    url: fe1024("Currency_Converter"),
    cover: fe1024img("Currency_Converter.png"),
  },
  {
    title: "Cut_the_rope",
    name: "Cut_the_rope",
    url: fe1024("Cut_the_rope"),
    cover: fe1024img("Cut_the_rope.webp"),
  },
];
