import { fe1024, fe1024img } from "../helper";

export default () => [
  {
    title: "DNA_Sequencer",
    name: "DNA_Sequencer",
    url: fe1024("DNA_Sequencer"),
    cover: fe1024img("DNA_Sequencer.png"),
  },
  {
    title: "Dante",
    name: "Dante",
    url: fe1024("Dante"),
    cover: fe1024img("Dante.png"),
  },
  {
    title: "Dead_Again",
    name: "Dead_Again",
    url: fe1024("Dead_Again"),
    cover: fe1024img("Dead_Again.png"),
  },
  {
    title: "Death_by_Hamster",
    name: "Death_by_Hamster",
    url: fe1024("Death_by_Hamster"),
    cover: fe1024img("Death_by_Hamster.png"),
  },
  {
    title: "Debris_Dodge",
    name: "Debris_Dodge",
    url: fe1024("Debris_Dodge"),
    cover: fe1024img("Debris_Dodge.png"),
  },
  {
    title: "Destroyer",
    name: "Destroyer",
    url: fe1024("Destroyer"),
    cover: fe1024img("Destroyer.png"),
  },
  {
    title: "Detona",
    name: "Detona",
    url: fe1024("Detona"),
    cover: fe1024img("Detona.png"),
  },
  {
    title: "Diamond_Run",
    name: "Diamond_Run",
    url: fe1024("Diamond_Run"),
    cover: fe1024img("Diamond_Run.png"),
  },
  {
    title: "Dice_Game",
    name: "Dice_Game",
    url: fe1024("Dice_Game"),
    cover: fe1024img("Dice_Game.png"),
  },
  {
    title: "Dice_Roller",
    name: "Dice_Roller",
    url: fe1024("Dice_Roller"),
    cover: fe1024img("Dice_Roller.png"),
  },
  {
    title: "Dice_Showdown_Game",
    name: "Dice_Showdown_Game",
    url: fe1024("Dice_Showdown_Game"),
    cover: fe1024img("Dice_Showdown_Game.png"),
  },
  {
    title: "Dice_rolling_simulator",
    name: "Dice_rolling_simulator",
    url: fe1024("Dice_rolling_simulator"),
    cover: fe1024img("Dice_rolling_simulator.png"),
  },
  {
    title: "Digit_Dilemma",
    name: "Digit_Dilemma",
    url: fe1024("Digit_Dilemma"),
    cover: fe1024img("Digit_Dilemma.png"),
  },
  {
    title: "Dino_Runner_Game",
    name: "Dino_Runner_Game",
    url: fe1024("Dino_Runner_Game"),
    cover: fe1024img("Dino_Runner_Game.png"),
  },
  {
    title: "Dinoffline",
    name: "Dinoffline",
    url: fe1024("Dinoffline"),
    cover: fe1024img("Dinoffline.png"),
  },
  {
    title: "Dinosaur_Memory_Game",
    name: "Dinosaur_Memory_Game",
    url: fe1024("Dinosaur_Memory_Game"),
    cover: fe1024img("Dinosaur_Memory_Game.png"),
  },
  {
    title: "Disney_Trivia",
    name: "Disney_Trivia",
    url: fe1024("Disney_Trivia"),
    cover: fe1024img("Disney_Trivia.png"),
  },
  {
    title: "Dodge the Blocks",
    name: "Dodge the Blocks",
    url: fe1024("Dodge the Blocks"),
    cover: fe1024img("Dodge the Blocks.png"),
  },
  {
    title: "Dont_Die_To_Ghosts",
    name: "Dont_Die_To_Ghosts",
    url: fe1024("Dont_Die_To_Ghosts"),
    cover: fe1024img("Dont_Die_To_Ghosts.png"),
  },
  {
    title: "Doodle_Draw",
    name: "Doodle_Draw",
    url: fe1024("Doodle_Draw"),
    cover: fe1024img("Doodle_Draw.png"),
  },
  {
    title: "Doodle_Jump",
    name: "Doodle_Jump",
    url: fe1024("Doodle_Jump"),
    cover: fe1024img("Doodle_Jump.png"),
  },
  {
    title: "Doppelkopf",
    name: "Doppelkopf",
    url: fe1024("Doppelkopf"),
    cover: fe1024img("Doppelkopf.png"),
  },
  {
    title: "DoraemonRun",
    name: "DoraemonRun",
    url: fe1024("DoraemonRun"),
    cover: fe1024img("DoraemonRun.png"),
  },
  {
    title: "Doraemon_Jump",
    name: "Doraemon_Jump",
    url: fe1024("Doraemon_Jump"),
    cover: fe1024img("Doraemon_Jump.png"),
  },
  {
    title: "Doremon_Puzzle",
    name: "Doremon_Puzzle",
    url: fe1024("Doremon_Puzzle"),
    cover: fe1024img("Doremon_Puzzle.png"),
  },
  {
    title: "Dot_Box_Game",
    name: "Dot_Box_Game",
    url: fe1024("Dot_Box_Game"),
    cover: fe1024img("Dot_Box_Game.png"),
  },
  {
    title: "Dot_Connect",
    name: "Dot_Connect",
    url: fe1024("Dot_Connect"),
    cover: fe1024img("Dot_Connect.png"),
  },
  {
    title: "Dot_Dash",
    name: "Dot_Dash",
    url: fe1024("Dot_Dash"),
    cover: fe1024img("Dot_Dash.png"),
  },
  {
    title: "Dots_and_Boxes_Game",
    name: "Dots_and_Boxes_Game",
    url: fe1024("Dots_and_Boxes_Game"),
    cover: fe1024img("Dots_and_Boxes_Game.png"),
  },
  {
    title: "Drag_And_Drop_Puzzle",
    name: "Drag_And_Drop_Puzzle",
    url: fe1024("Drag_And_Drop_Puzzle"),
    cover: fe1024img("Drag_And_Drop_Puzzle.png"),
  },
  {
    title: "Dragon_Ball_Game",
    name: "Dragon_Ball_Game",
    url: fe1024("Dragon_Ball_Game"),
    cover: fe1024img("Dragon_Ball_Game.png"),
  },
  {
    title: "Dragon_Slayer",
    name: "Dragon_Slayer",
    url: fe1024("Dragon_Slayer"),
    cover: fe1024img("Dragon_Slayer.png"),
  },
  {
    title: "Dragon_Tower",
    name: "Dragon_Tower",
    url: fe1024("Dragon_Tower"),
    cover: fe1024img("Dragon_Tower.png"),
  },
  {
    title: "Dragon_World_Game",
    name: "Dragon_World_Game",
    url: fe1024("Dragon_World_Game"),
    cover: fe1024img("Dragon_World_Game.png"),
  },
  {
    title: "Drawing_app",
    name: "Drawing_app",
    url: fe1024("Drawing_app"),
    cover: fe1024img("Drawing_app.png"),
  },
  {
    title: "Drop_Dash_Game",
    name: "Drop_Dash_Game",
    url: fe1024("Drop_Dash_Game"),
    cover: fe1024img("Drop_Dash_Game.png"),
  },
  {
    title: "Drum_Kit_Game",
    name: "Drum_Kit_Game",
    url: fe1024("Drum_Kit_Game"),
    cover: fe1024img("Drum_Kit_Game.png"),
  },
  {
    title: "Drum_kit",
    name: "Drum_kit",
    url: fe1024("Drum_kit"),
    cover: fe1024img("Drum_kit.png"),
  },
  {
    title: "Drummer_Kit",
    name: "Drummer_Kit",
    url: fe1024("Drummer_Kit"),
    cover: fe1024img("Drummer_Kit.png"),
  },
  {
    title: "Dsa_quiz_game",
    name: "Dsa_quiz_game",
    url: fe1024("Dsa_quiz_game"),
    cover: fe1024img("Dsa_quiz_game.png"),
  },
  {
    title: "DuckHunt",
    name: "DuckHunt",
    url: fe1024("DuckHunt"),
    cover: fe1024img("DuckHunt.png"),
  },
  {
    title: "Duck_Hunting_Game",
    name: "Duck_Hunting_Game",
    url: fe1024("Duck_Hunting_Game"),
    cover: fe1024img("Duck_Hunting_Game.png"),
  },
  {
    title: "Dungeon_Crawler",
    name: "Dungeon_Crawler",
    url: fe1024("Dungeon_Crawler"),
    cover: fe1024img("Dungeon_Crawler.png"),
  },
  {
    title: "Earth_Destroyer",
    name: "Earth_Destroyer",
    url: fe1024("Earth_Destroyer"),
    cover: fe1024img("Earth_Destroyer.png"),
  },
  {
    title: "Earth_Guardian",
    name: "Earth_Guardian",
    url: fe1024("Earth_Guardian"),
    cover: fe1024img("Earth_Guardian.png"),
  },
  {
    title: "Eco_Warrior",
    name: "Eco_Warrior",
    url: fe1024("Eco_Warrior"),
    cover: fe1024img("Eco_Warrior.png"),
  },
  {
    title: "Elemental Riddles",
    name: "Elemental Riddles",
    url: fe1024("Elemental Riddles"),
    cover: fe1024img("Elemental Riddles.png"),
  },
  {
    title: "Elemental_Flux",
    name: "Elemental_Flux",
    url: fe1024("Elemental_Flux"),
    cover: fe1024img("Elemental_Flux.png"),
  },
  {
    title: "Elephant_ant_man",
    name: "Elephant_ant_man",
    url: fe1024("Elephant_ant_man"),
    cover: fe1024img("Elephant_ant_man.png"),
  },
  {
    title: "Emoji_Charades",
    name: "Emoji_Charades",
    url: fe1024("Emoji_Charades"),
    cover: fe1024img("Emoji_Charades.png"),
  },
  {
    title: "Emoji_Intruder",
    name: "Emoji_Intruder",
    url: fe1024("Emoji_Intruder"),
    cover: fe1024img("Emoji_Intruder.png"),
  },
  {
    title: "Emoji_Puzzle_Game",
    name: "Emoji_Puzzle_Game",
    url: fe1024("Emoji_Puzzle_Game"),
    cover: fe1024img("Emoji_Puzzle_Game.png"),
  },
  {
    title: "Emoji_slot_machine",
    name: "Emoji_slot_machine",
    url: fe1024("Emoji_slot_machine"),
    cover: fe1024img("Emoji_slot_machine.png"),
  },
  {
    title: "EndlessRunner",
    name: "EndlessRunner",
    url: fe1024("EndlessRunner"),
    cover: fe1024img("EndlessRunner.png"),
  },
  {
    title: "Escape",
    name: "Escape",
    url: fe1024("Escape"),
    cover: fe1024img("Escape.png"),
  },
  {
    title: "Escape_room",
    name: "Escape_room",
    url: fe1024("Escape_room"),
    cover: fe1024img("Escape_room.png"),
  },
  {
    title: "Etch_a_Sketch",
    name: "Etch_a_Sketch",
    url: fe1024("Etch_a_Sketch"),
    cover: fe1024img("Etch_a_Sketch.png"),
  },
  {
    title: "Etch_a_Sketch_2",
    name: "Etch_a_Sketch_2",
    url: fe1024("Etch_a_Sketch_2"),
    cover: fe1024img("Etch_a_Sketch_2.png"),
  },
  {
    title: "Everyones_Sky",
    name: "Everyones_Sky",
    url: fe1024("Everyones_Sky"),
    cover: fe1024img("Everyones_Sky.png"),
  },
  {
    title: "Fall_Down",
    name: "Fall_Down",
    url: fe1024("Fall_Down"),
    cover: fe1024img("Fall_Down.png"),
  },
  {
    title: "Falling_Ball",
    name: "Falling_Ball",
    url: fe1024("Falling_Ball"),
    cover: fe1024img("Falling_Ball.png"),
  },
  {
    title: "Falling_Blocks",
    name: "Falling_Blocks",
    url: fe1024("Falling_Blocks"),
    cover: fe1024img("Falling_Blocks.png"),
  },
  {
    title: "Falling_Words",
    name: "Falling_Words",
    url: fe1024("Falling_Words"),
    cover: fe1024img("Falling_Words.png"),
  },
  {
    title: "Fidget_Spinner_Game",
    name: "Fidget_Spinner_Game",
    url: fe1024("Fidget_Spinner_Game"),
    cover: fe1024img("Fidget_Spinner_Game.png"),
  },
  {
    title: "Fifteen_Puzzle_Game",
    name: "Fifteen_Puzzle_Game",
    url: fe1024("Fifteen_Puzzle_Game"),
    cover: fe1024img("Fifteen_Puzzle_Game.png"),
  },
  {
    title: "Fight_Game",
    name: "Fight_Game",
    url: fe1024("Fight_Game"),
    cover: fe1024img("Fight_Game.png"),
  },
  {
    title: "Find_Extra_Cube",
    name: "Find_Extra_Cube",
    url: fe1024("Find_Extra_Cube"),
    cover: fe1024img("Find_Extra_Cube.png"),
  },
  {
    title: "Find_The_Missing_Letter",
    name: "Find_The_Missing_Letter",
    url: fe1024("Find_The_Missing_Letter"),
    cover: fe1024img("Find_The_Missing_Letter.png"),
  },
  {
    title: "Find_the_Number",
    name: "Find_the_Number",
    url: fe1024("Find_the_Number"),
    cover: fe1024img("Find_the_Number.png"),
  },
  {
    title: "Find_the_ball",
    name: "Find_the_ball",
    url: fe1024("Find_the_ball"),
    cover: fe1024img("Find_the_ball.png"),
  },
  {
    title: "Firedog_Adventure",
    name: "Firedog_Adventure",
    url: fe1024("Firedog_Adventure"),
    cover: fe1024img("Firedog_Adventure.png"),
  },
  {
    title: "Five_Nights_at_Freddys",
    name: "Five_Nights_at_Freddys",
    url: fe1024("Five_Nights_at_Freddys"),
    cover: fe1024img("Five_Nights_at_Freddys.png"),
  },
  {
    title: "Flag_Guess_Game",
    name: "Flag_Guess_Game",
    url: fe1024("Flag_Guess_Game"),
    cover: fe1024img("Flag_Guess_Game.png"),
  },
  {
    title: "Flames Game",
    name: "Flames Game",
    url: fe1024("Flames Game"),
    cover: fe1024img("Flames Game.png"),
  },
  {
    title: "Flappy_Bird",
    name: "Flappy_Bird",
    url: fe1024("Flappy_Bird"),
    cover: fe1024img("Flappy_Bird.png"),
  },
  {
    title: "Flappy_Birdd",
    name: "Flappy_Birdd",
    url: fe1024("Flappy_Birdd"),
    cover: fe1024img("Flappy_Birdd.png"),
  },
  {
    title: "Flappy_Bubble_Sofa",
    name: "Flappy_Bubble_Sofa",
    url: fe1024("Flappy_Bubble_Sofa"),
    cover: fe1024img("Flappy_Bubble_Sofa.png"),
  },
  {
    title: "Flashlight_Pointer_Game",
    name: "Flashlight_Pointer_Game",
    url: fe1024("Flashlight_Pointer_Game"),
    cover: fe1024img("Flashlight_Pointer_Game.png"),
  },
  {
    title: "Flip_Card_Game",
    name: "Flip_Card_Game",
    url: fe1024("Flip_Card_Game"),
    cover: fe1024img("Flip_Card_Game.png"),
  },
  {
    title: "Flip_Coin",
    name: "Flip_Coin",
    url: fe1024("Flip_Coin"),
    cover: fe1024img("Flip_Coin.png"),
  },
  {
    title: "Flying_Fish",
    name: "Flying_Fish",
    url: fe1024("Flying_Fish"),
    cover: fe1024img("Flying_Fish.png"),
  },
  {
    title: "Foosball",
    name: "Foosball",
    url: fe1024("Foosball"),
    cover: fe1024img("Foosball.png"),
  },
  {
    title: "Forest_Guardian",
    name: "Forest_Guardian",
    url: fe1024("Forest_Guardian"),
    cover: fe1024img("Forest_Guardian.png"),
  },
  {
    title: "Four_In_Row",
    name: "Four_In_Row",
    url: fe1024("Four_In_Row"),
    cover: fe1024img("Four_In_Row.png"),
  },
  {
    title: "Free_Bird",
    name: "Free_Bird",
    url: fe1024("Free_Bird"),
    cover: fe1024img("Free_Bird.png"),
  },
  {
    title: "Frogger",
    name: "Frogger",
    url: fe1024("Frogger"),
    cover: fe1024img("Frogger.png"),
  },
  {
    title: "FruitCatcher",
    name: "FruitCatcher",
    url: fe1024("FruitCatcher"),
    cover: fe1024img("FruitCatcher.png"),
  },
  {
    title: "Fruit_Catching",
    name: "Fruit_Catching",
    url: fe1024("Fruit_Catching"),
    cover: fe1024img("Fruit_Catching.png"),
  },
  {
    title: "Fruit_Catching_Game",
    name: "Fruit_Catching_Game",
    url: fe1024("Fruit_Catching_Game"),
    cover: fe1024img("Fruit_Catching_Game.png"),
  },
  {
    title: "Fruit_Ninja",
    name: "Fruit_Ninja",
    url: fe1024("Fruit_Ninja"),
    cover: fe1024img("Fruit_Ninja.png"),
  },
  {
    title: "Fruit_Slicer_Game",
    name: "Fruit_Slicer_Game",
    url: fe1024("Fruit_Slicer_Game"),
    cover: fe1024img("Fruit_Slicer_Game.png"),
  },
  {
    title: "Fruity_Fortune",
    name: "Fruity_Fortune",
    url: fe1024("Fruity_Fortune"),
    cover: fe1024img("Fruity_Fortune.png"),
  },
  {
    title: "Galaxy-Shoot",
    name: "Galaxy-Shoot",
    url: fe1024("Galaxy-Shoot"),
    cover: fe1024img("Galaxy-Shoot.png"),
  },
  {
    title: "Galaxy_Rider",
    name: "Galaxy_Rider",
    url: fe1024("Galaxy_Rider"),
    cover: fe1024img("Galaxy_Rider.png"),
  },
  {
    title: "Ganesh QR Maker",
    name: "Ganesh QR Maker",
    url: fe1024("Ganesh QR Maker"),
    cover: fe1024img("Ganesh QR Maker.png"),
  },
  {
    title: "Garden-Builder-game",
    name: "Garden-Builder-game",
    url: fe1024("Garden-Builder-game"),
    cover: fe1024img("Garden-Builder-game.png"),
  },
  {
    title: "Gem_Cruncher",
    name: "Gem_Cruncher",
    url: fe1024("Gem_Cruncher"),
    cover: fe1024img("Gem_Cruncher.png"),
  },
  {
    title: "Get_The_Pigeon",
    name: "Get_The_Pigeon",
    url: fe1024("Get_The_Pigeon"),
    cover: fe1024img("Get_The_Pigeon.png"),
  },
  {
    title: "Ghost_Surf",
    name: "Ghost_Surf",
    url: fe1024("Ghost_Surf"),
    cover: fe1024img("Ghost_Surf.png"),
  },
  {
    title: "Ghost_busting_game",
    name: "Ghost_busting_game",
    url: fe1024("Ghost_busting_game"),
    cover: fe1024img("Ghost_busting_game.png"),
  },
  {
    title: "Gita_Shloka_Generator",
    name: "Gita_Shloka_Generator",
    url: fe1024("Gita_Shloka_Generator"),
    cover: fe1024img("Gita_Shloka_Generator.png"),
  },
  {
    title: "Glitch_Buster",
    name: "Glitch_Buster",
    url: fe1024("Glitch_Buster"),
    cover: fe1024img("Glitch_Buster.png"),
  },
  {
    title: "Gnomedom",
    name: "Gnomedom",
    url: fe1024("Gnomedom"),
    cover: fe1024img("Gnomedom.png"),
  },
  {
    title: "Go-fish-master",
    name: "Go-fish-master",
    url: fe1024("Go-fish-master"),
    cover: fe1024img("Go-fish-master.png"),
  },
  {
    title: "GoFish",
    name: "GoFish",
    url: fe1024("GoFish"),
    cover: fe1024img("GoFish.png"),
  },
  {
    title: "Goal_Rush",
    name: "Goal_Rush",
    url: fe1024("Goal_Rush"),
    cover: fe1024img("Goal_Rush.png"),
  },
  {
    title: "Gobblet",
    name: "Gobblet",
    url: fe1024("Gobblet"),
    cover: fe1024img("Gobblet.png"),
  },
  {
    title: "Grab_The_Carrot",
    name: "Grab_The_Carrot",
    url: fe1024("Grab_The_Carrot"),
    cover: fe1024img("Grab_The_Carrot.png"),
  },
  {
    title: "Gravity_Dropss",
    name: "Gravity_Dropss",
    url: fe1024("Gravity_Dropss"),
    cover: fe1024img("Gravity_Dropss.png"),
  },
  {
    title: "Gravity_Simulation_Game",
    name: "Gravity_Simulation_Game",
    url: fe1024("Gravity_Simulation_Game"),
    cover: fe1024img("Gravity_Simulation_Game.png"),
  },
  {
    title: "Gravity_Switch_Game",
    name: "Gravity_Switch_Game",
    url: fe1024("Gravity_Switch_Game"),
    cover: fe1024img("Gravity_Switch_Game.png"),
  },
  {
    title: "Green_Mahjong",
    name: "Green_Mahjong",
    url: fe1024("Green_Mahjong"),
    cover: fe1024img("Green_Mahjong.png"),
  },
  {
    title: "Guess_That_Pokemon",
    name: "Guess_That_Pokemon",
    url: fe1024("Guess_That_Pokemon"),
    cover: fe1024img("Guess_That_Pokemon.png"),
  },
  {
    title: "Guess_The_Ball",
    name: "Guess_The_Ball",
    url: fe1024("Guess_The_Ball"),
    cover: fe1024img("Guess_The_Ball.png"),
  },
  {
    title: "Guess_The_Celeb",
    name: "Guess_The_Celeb",
    url: fe1024("Guess_The_Celeb"),
    cover: fe1024img("Guess_The_Celeb.png"),
  },
  {
    title: "Guess_The_Correct_Logo",
    name: "Guess_The_Correct_Logo",
    url: fe1024("Guess_The_Correct_Logo"),
    cover: fe1024img("Guess_The_Correct_Logo.png"),
  },
  {
    title: "Guess_The_Murderer",
    name: "Guess_The_Murderer",
    url: fe1024("Guess_The_Murderer"),
    cover: fe1024img("Guess_The_Murderer.png"),
  },
  {
    title: "Guess_The_Number",
    name: "Guess_The_Number",
    url: fe1024("Guess_The_Number"),
    cover: fe1024img("Guess_The_Number.png"),
  },
  {
    title: "Guess_The_Random_Shape",
    name: "Guess_The_Random_Shape",
    url: fe1024("Guess_The_Random_Shape"),
    cover: fe1024img("Guess_The_Random_Shape.png"),
  },
  {
    title: "Guess_The_Song",
    name: "Guess_The_Song",
    url: fe1024("Guess_The_Song"),
    cover: fe1024img("Guess_The_Song.png"),
  },
  {
    title: "Guess_The_Weapon",
    name: "Guess_The_Weapon",
    url: fe1024("Guess_The_Weapon"),
    cover: fe1024img("Guess_The_Weapon.png"),
  },
  {
    title: "Guess_Who",
    name: "Guess_Who",
    url: fe1024("Guess_Who"),
    cover: fe1024img("Guess_Who.png"),
  },
  {
    title: "Guess_num",
    name: "Guess_num",
    url: fe1024("Guess_num"),
    cover: fe1024img("Guess_num.png"),
  },
  {
    title: "Guess_the_friends_name",
    name: "Guess_the_friends_name",
    url: fe1024("Guess_the_friends_name"),
    cover: fe1024img("Guess_the_friends_name.png"),
  },
  {
    title: "Guitar_Game",
    name: "Guitar_Game",
    url: fe1024("Guitar_Game"),
    cover: fe1024img("Guitar_Game.png"),
  },
];
