import { fe1024, fe1024img } from "../helper";

export default () => [
  {
    title: "HTML5_Controller_Tester",
    name: "HTML5_Controller_Tester",
    url: fe1024("HTML5_Controller_Tester"),
    cover: fe1024img("HTML5_Controller_Tester.png"),
  },
  {
    title: "Hand_Cricket",
    name: "Hand_Cricket",
    url: fe1024("Hand_Cricket"),
    cover: fe1024img("Hand_Cricket.png"),
  },
  {
    title: "HangMan",
    name: "HangMan",
    url: fe1024("HangMan"),
    cover: fe1024img("HangMan.png"),
  },
  {
    title: "Hangman_Game",
    name: "Hangman_Game",
    url: fe1024("Hangman_Game"),
    cover: fe1024img("Hangman_Game.png"),
  },
  {
    title: "Harmony_Mixer",
    name: "Harmony_Mixer",
    url: fe1024("Harmony_Mixer"),
    cover: fe1024img("Harmony_Mixer.png"),
  },
  {
    title: "Harry_Potter_Wizard_Quiz",
    name: "Harry_Potter_Wizard_Quiz",
    url: fe1024("Harry_Potter_Wizard_Quiz"),
    cover: fe1024img("Harry_Potter_Wizard_Quiz.png"),
  },
  {
    title: "Hedgehog_Havoc",
    name: "Hedgehog_Havoc",
    url: fe1024("Hedgehog_Havoc"),
    cover: fe1024img("Hedgehog_Havoc.png"),
  },
  {
    title: "Helicopter_Game",
    name: "Helicopter_Game",
    url: fe1024("Helicopter_Game"),
    cover: fe1024img("Helicopter_Game.png"),
  },
  {
    title: "Hexsweep-Game",
    name: "Hexsweep-Game",
    url: fe1024("Hexsweep-Game"),
    cover: fe1024img("Hexsweep-Game.png"),
  },
  {
    title: "Hextris",
    name: "Hextris",
    url: fe1024("Hextris"),
    cover: fe1024img("Hextris.png"),
  },
  {
    title: "Hide_And_Seek",
    name: "Hide_And_Seek",
    url: fe1024("Hide_And_Seek"),
    cover: fe1024img("Hide_And_Seek.png"),
  },
  {
    title: "Highway_404",
    name: "Highway_404",
    url: fe1024("Highway_404"),
    cover: fe1024img("Highway_404.png"),
  },
  {
    title: "Highway_Race",
    name: "Highway_Race",
    url: fe1024("Highway_Race"),
    cover: fe1024img("Highway_Race.png"),
  },
  {
    title: "HitOrMiss",
    name: "HitOrMiss",
    url: fe1024("HitOrMiss"),
    cover: fe1024img("HitOrMiss.png"),
  },
  {
    title: "HitYourFriend",
    name: "HitYourFriend",
    url: fe1024("HitYourFriend"),
    cover: fe1024img("HitYourFriend.png"),
  },
  {
    title: "Hit_Target",
    name: "Hit_Target",
    url: fe1024("Hit_Target"),
    cover: fe1024img("Hit_Target.png"),
  },
  {
    title: "Hit_The_Mole",
    name: "Hit_The_Mole",
    url: fe1024("Hit_The_Mole"),
    cover: fe1024img("Hit_The_Mole.png"),
  },
  {
    title: "Hit_the_hamster",
    name: "Hit_the_hamster",
    url: fe1024("Hit_the_hamster"),
    cover: fe1024img("Hit_the_hamster.png"),
  },
  {
    title: "Hold_The_Cloud",
    name: "Hold_The_Cloud",
    url: fe1024("Hold_The_Cloud"),
    cover: fe1024img("Hold_The_Cloud.png"),
  },
  {
    title: "Hole_And_Mole_Game",
    name: "Hole_And_Mole_Game",
    url: fe1024("Hole_And_Mole_Game"),
    cover: fe1024img("Hole_And_Mole_Game.png"),
  },
  {
    title: "Hover_Board_Effect",
    name: "Hover_Board_Effect",
    url: fe1024("Hover_Board_Effect"),
    cover: fe1024img("Hover_Board_Effect.png"),
  },
  {
    title: "HueHero",
    name: "HueHero",
    url: fe1024("HueHero"),
    cover: fe1024img("HueHero.png"),
  },
  {
    title: "Humming",
    name: "Humming",
    url: fe1024("Humming"),
    cover: fe1024img("Humming.png"),
  },
  {
    title: "Hunt_Your_Card",
    name: "Hunt_Your_Card",
    url: fe1024("Hunt_Your_Card"),
    cover: fe1024img("Hunt_Your_Card.png"),
  },
  {
    title: "IKnowYou-Mind-Reading-Game",
    name: "IKnowYou-Mind-Reading-Game",
    url: fe1024("IKnowYou-Mind-Reading-Game"),
    cover: fe1024img("IKnowYou-Mind-Reading-Game.png"),
  },
  {
    title: "I_Want_To_Google_The_Game",
    name: "I_Want_To_Google_The_Game",
    url: fe1024("I_Want_To_Google_The_Game"),
    cover: fe1024img("I_Want_To_Google_The_Game.png"),
  },
  {
    title: "Icy_Tower_Game",
    name: "Icy_Tower_Game",
    url: fe1024("Icy_Tower_Game"),
    cover: fe1024img("Icy_Tower_Game.png"),
  },
  {
    title: "Idle_miner",
    name: "Idle_miner",
    url: fe1024("Idle_miner"),
    cover: fe1024img("Idle_miner.png"),
  },
  {
    title: "Illusion",
    name: "Illusion",
    url: fe1024("Illusion"),
    cover: fe1024img("Illusion.png"),
  },
  {
    title: "Immunity_Collapse",
    name: "Immunity_Collapse",
    url: fe1024("Immunity_Collapse"),
    cover: fe1024img("Immunity_Collapse.png"),
  },
  {
    title: "Infernal_Throne",
    name: "Infernal_Throne",
    url: fe1024("Infernal_Throne"),
    cover: fe1024img("Infernal_Throne.png"),
  },
  {
    title: "Infinite_Cars",
    name: "Infinite_Cars",
    url: fe1024("Infinite_Cars"),
    cover: fe1024img("Infinite_Cars.png"),
  },
  {
    title: "Infinite_Runner_Game",
    name: "Infinite_Runner_Game",
    url: fe1024("Infinite_Runner_Game"),
    cover: fe1024img("Infinite_Runner_Game.png"),
  },
  {
    title: "Insect_Catch_Game",
    name: "Insect_Catch_Game",
    url: fe1024("Insect_Catch_Game"),
    cover: fe1024img("Insect_Catch_Game.png"),
  },
  {
    title: "Intellect_Quest",
    name: "Intellect_Quest",
    url: fe1024("Intellect_Quest"),
    cover: fe1024img("Intellect_Quest.png"),
  },
  {
    title: "Interactive_Quizzing",
    name: "Interactive_Quizzing",
    url: fe1024("Interactive_Quizzing"),
    cover: fe1024img("Interactive_Quizzing.png"),
  },
  {
    title: "Island_Survival",
    name: "Island_Survival",
    url: fe1024("Island_Survival"),
    cover: fe1024img("Island_Survival.png"),
  },
  {
    title: "Jigsaw_Puzzle",
    name: "Jigsaw_Puzzle",
    url: fe1024("Jigsaw_Puzzle"),
    cover: fe1024img("Jigsaw_Puzzle.png"),
  },
  {
    title: "Johnny_Smiter",
    name: "Johnny_Smiter",
    url: fe1024("Johnny_Smiter"),
    cover: fe1024img("Johnny_Smiter.png"),
  },
  {
    title: "JunoJs",
    name: "JunoJs",
    url: fe1024("JunoJs"),
    cover: fe1024img("JunoJs.png"),
  },
  {
    title: "Keyboard_Hero",
    name: "Keyboard_Hero",
    url: fe1024("Keyboard_Hero"),
    cover: fe1024img("Keyboard_Hero.png"),
  },
  {
    title: "Kill_The_Bird",
    name: "Kill_The_Bird",
    url: fe1024("Kill_The_Bird"),
    cover: fe1024img("Kill_The_Bird.png"),
  },
  {
    title: "King_Of_Pirates_Quiz",
    name: "King_Of_Pirates_Quiz",
    url: fe1024("King_Of_Pirates_Quiz"),
    cover: fe1024img("King_Of_Pirates_Quiz.png"),
  },
  {
    title: "King_Sword_Runner",
    name: "King_Sword_Runner",
    url: fe1024("King_Sword_Runner"),
    cover: fe1024img("King_Sword_Runner.png"),
  },
  {
    title: "Knife-Thrower",
    name: "Knife-Thrower",
    url: fe1024("Knife-Thrower"),
    cover: fe1024img("Knife-Thrower.png"),
  },
  {
    title: "Knife_hit",
    name: "Knife_hit",
    url: fe1024("Knife_hit"),
    cover: fe1024img("Knife_hit.png"),
  },
  {
    title: "Know_Your_Country",
    name: "Know_Your_Country",
    url: fe1024("Know_Your_Country"),
    cover: fe1024img("Know_Your_Country.png"),
  },
  {
    title: "LOSSST",
    name: "LOSSST",
    url: fe1024("LOSSST"),
    cover: fe1024img("LOSSST.png"),
  },
  {
    title: "Labyrinth",
    name: "Labyrinth",
    url: fe1024("Labyrinth"),
    cover: fe1024img("Labyrinth.png"),
  },
  {
    title: "Lady_Tiger_Hunter",
    name: "Lady_Tiger_Hunter",
    url: fe1024("Lady_Tiger_Hunter"),
    cover: fe1024img("Lady_Tiger_Hunter.png"),
  },
  {
    title: "Lamb_Lane",
    name: "Lamb_Lane",
    url: fe1024("Lamb_Lane"),
    cover: fe1024img("Lamb_Lane.png"),
  },
  {
    title: "Language_Learner_Adventure",
    name: "Language_Learner_Adventure",
    url: fe1024("Language_Learner_Adventure"),
    cover: fe1024img("Language_Learner_Adventure.png"),
  },
  {
    title: "LaserDarts",
    name: "LaserDarts",
    url: fe1024("LaserDarts"),
    cover: fe1024img("LaserDarts.png"),
  },
  {
    title: "Letter_Sleuth",
    name: "Letter_Sleuth",
    url: fe1024("Letter_Sleuth"),
    cover: fe1024img("Letter_Sleuth.png"),
  },
  {
    title: "Lighthouse",
    name: "Lighthouse",
    url: fe1024("Lighthouse"),
    cover: fe1024img("Lighthouse.png"),
  },
  {
    title: "Lights_Out",
    name: "Lights_Out",
    url: fe1024("Lights_Out"),
    cover: fe1024img("Lights_Out.png"),
  },
  {
    title: "Line_Of_Fire",
    name: "Line_Of_Fire",
    url: fe1024("Line_Of_Fire"),
    cover: fe1024img("Line_Of_Fire.png"),
  },
  {
    title: "Little_Red_Game",
    name: "Little_Red_Game",
    url: fe1024("Little_Red_Game"),
    cover: fe1024img("Little_Red_Game.png"),
  },
  {
    title: "Lizard_Spock_Game",
    name: "Lizard_Spock_Game",
    url: fe1024("Lizard_Spock_Game"),
    cover: fe1024img("Lizard_Spock_Game.png"),
  },
  {
    title: "Lonely_Phantom",
    name: "Lonely_Phantom",
    url: fe1024("Lonely_Phantom"),
    cover: fe1024img("Lonely_Phantom.png"),
  },
  {
    title: "Lost_In_The_Maze_3D",
    name: "Lost_In_The_Maze_3D",
    url: fe1024("Lost_In_The_Maze_3D"),
    cover: fe1024img("Lost_In_The_Maze_3D.png"),
  },
  {
    title: "Love Calculator Game",
    name: "Love Calculator Game",
    url: fe1024("Love Calculator Game"),
    cover: fe1024img("Love Calculator Game.png"),
  },
  {
    title: "Love_Calci",
    name: "Love_Calci",
    url: fe1024("Love_Calci"),
    cover: fe1024img("Love_Calci.png"),
  },
  {
    title: "Love_Result_Predictor",
    name: "Love_Result_Predictor",
    url: fe1024("Love_Result_Predictor"),
    cover: fe1024img("Love_Result_Predictor.png"),
  },
  {
    title: "Ludo_4_Player",
    name: "Ludo_4_Player",
    url: fe1024("Ludo_4_Player"),
    cover: fe1024img("Ludo_4_Player.png"),
  },
  {
    title: "Ludo_Game",
    name: "Ludo_Game",
    url: fe1024("Ludo_Game"),
    cover: fe1024img("Ludo_Game.png"),
  },
  {
    title: "Lunar_Lander",
    name: "Lunar_Lander",
    url: fe1024("Lunar_Lander"),
    cover: fe1024img("Lunar_Lander.png"),
  },
  {
    title: "Madlibs",
    name: "Madlibs",
    url: fe1024("Madlibs"),
    cover: fe1024img("Madlibs.png"),
  },
  {
    title: "Magic_8_ball",
    name: "Magic_8_ball",
    url: fe1024("Magic_8_ball"),
    cover: fe1024img("Magic_8_ball.png"),
  },
  {
    title: "Magic_Square",
    name: "Magic_Square",
    url: fe1024("Magic_Square"),
    cover: fe1024img("Magic_Square.png"),
  },
  {
    title: "Make_Me_Laugh",
    name: "Make_Me_Laugh",
    url: fe1024("Make_Me_Laugh"),
    cover: fe1024img("Make_Me_Laugh.png"),
  },
  {
    title: "Makeover_Game",
    name: "Makeover_Game",
    url: fe1024("Makeover_Game"),
    cover: fe1024img("Makeover_Game.png"),
  },
  {
    title: "Mamba_Mayhem",
    name: "Mamba_Mayhem",
    url: fe1024("Mamba_Mayhem"),
    cover: fe1024img("Mamba_Mayhem.png"),
  },
  {
    title: "Mancala_Game",
    name: "Mancala_Game",
    url: fe1024("Mancala_Game"),
    cover: fe1024img("Mancala_Game.png"),
  },
  {
    title: "Mansion_Mystery",
    name: "Mansion_Mystery",
    url: fe1024("Mansion_Mystery"),
    cover: fe1024img("Mansion_Mystery.png"),
  },
  {
    title: "Mastemind",
    name: "Mastemind",
    url: fe1024("Mastemind"),
    cover: fe1024img("Mastemind.png"),
  },
  {
    title: "Master_Typing",
    name: "Master_Typing",
    url: fe1024("Master_Typing"),
    cover: fe1024img("Master_Typing.png"),
  },
  {
    title: "Mastermind_Mania",
    name: "Mastermind_Mania",
    url: fe1024("Mastermind_Mania"),
    cover: fe1024img("Mastermind_Mania.png"),
  },
  {
    title: "Match_Color_Game",
    name: "Match_Color_Game",
    url: fe1024("Match_Color_Game"),
    cover: fe1024img("Match_Color_Game.png"),
  },
  {
    title: "Matching_pair",
    name: "Matching_pair",
    url: fe1024("Matching_pair"),
    cover: fe1024img("Matching_pair.png"),
  },
  {
    title: "MathQuiz",
    name: "MathQuiz",
    url: fe1024("MathQuiz"),
    cover: fe1024img("MathQuiz.png"),
  },
  {
    title: "Math_Game",
    name: "Math_Game",
    url: fe1024("Math_Game"),
    cover: fe1024img("Math_Game.png"),
  },
  {
    title: "Math_Race_Game",
    name: "Math_Race_Game",
    url: fe1024("Math_Race_Game"),
    cover: fe1024img("Math_Race_Game.png"),
  },
  {
    title: "MathematicsEscapeRoom",
    name: "MathematicsEscapeRoom",
    url: fe1024("MathematicsEscapeRoom"),
    cover: fe1024img("MathematicsEscapeRoom.png"),
  },
  {
    title: "Maths_Sprint_Game",
    name: "Maths_Sprint_Game",
    url: fe1024("Maths_Sprint_Game"),
    cover: fe1024img("Maths_Sprint_Game.png"),
  },
  {
    title: "MaximiseBoxes",
    name: "MaximiseBoxes",
    url: fe1024("MaximiseBoxes"),
    cover: fe1024img("MaximiseBoxes.png"),
  },
  {
    title: "MazeGame",
    name: "MazeGame",
    url: fe1024("MazeGame"),
    cover: fe1024img("MazeGame.png"),
  },
  {
    title: "MazeRunner",
    name: "MazeRunner",
    url: fe1024("MazeRunner"),
    cover: fe1024img("MazeRunner.png"),
  },
  {
    title: "Maze_Explorer",
    name: "Maze_Explorer",
    url: fe1024("Maze_Explorer"),
    cover: fe1024img("Maze_Explorer.png"),
  },
  {
    title: "Maze_Game",
    name: "Maze_Game",
    url: fe1024("Maze_Game"),
    cover: fe1024img("Maze_Game.png"),
  },
  {
    title: "Maze_Runner",
    name: "Maze_Runner",
    url: fe1024("Maze_Runner"),
    cover: fe1024img("Maze_Runner.png"),
  },
  {
    title: "Maze_of_Cables",
    name: "Maze_of_Cables",
    url: fe1024("Maze_of_Cables"),
    cover: fe1024img("Maze_of_Cables.png"),
  },
  {
    title: "Mechanica",
    name: "Mechanica",
    url: fe1024("Mechanica"),
    cover: fe1024img("Mechanica.png"),
  },
  {
    title: "Meme_Battle_Game",
    name: "Meme_Battle_Game",
    url: fe1024("Meme_Battle_Game"),
    cover: fe1024img("Meme_Battle_Game.png"),
  },
  {
    title: "Memorization_card",
    name: "Memorization_card",
    url: fe1024("Memorization_card"),
    cover: fe1024img("Memorization_card.png"),
  },
  {
    title: "Memory Flip",
    name: "Memory Flip",
    url: fe1024("Memory Flip"),
    cover: fe1024img("Memory Flip.png"),
  },
  {
    title: "Memory_Card",
    name: "Memory_Card",
    url: fe1024("Memory_Card"),
    cover: fe1024img("Memory_Card.png"),
  },
  {
    title: "Memory_Cards_Game",
    name: "Memory_Cards_Game",
    url: fe1024("Memory_Cards_Game"),
    cover: fe1024img("Memory_Cards_Game.png"),
  },
  {
    title: "Memory_Game",
    name: "Memory_Game",
    url: fe1024("Memory_Game"),
    cover: fe1024img("Memory_Game.png"),
  },
  {
    title: "Memory_Matching_Game",
    name: "Memory_Matching_Game",
    url: fe1024("Memory_Matching_Game"),
    cover: fe1024img("Memory_Matching_Game.png"),
  },
  {
    title: "Menja",
    name: "Menja",
    url: fe1024("Menja"),
    cover: fe1024img("Menja.png"),
  },
  {
    title: "Menja_block_breaker",
    name: "Menja_block_breaker",
    url: fe1024("Menja_block_breaker"),
    cover: fe1024img("Menja_block_breaker.png"),
  },
  {
    title: "MineSweeper_Easy",
    name: "MineSweeper_Easy",
    url: fe1024("MineSweeper_Easy"),
    cover: fe1024img("MineSweeper_Easy.png"),
  },
  {
    title: "Minecraft",
    name: "Minecraft",
    url: fe1024("Minecraft"),
    cover: fe1024img("Minecraft.png"),
  },
  {
    title: "Minesweeper",
    name: "Minesweeper",
    url: fe1024("Minesweeper"),
    cover: fe1024img("Minesweeper.png"),
  },
  {
    title: "Mini_Golf",
    name: "Mini_Golf",
    url: fe1024("Mini_Golf"),
    cover: fe1024img("Mini_Golf.png"),
  },
  {
    title: "Modulo_Game",
    name: "Modulo_Game",
    url: fe1024("Modulo_Game"),
    cover: fe1024img("Modulo_Game.png"),
  },
  {
    title: "Mole",
    name: "Mole",
    url: fe1024("Mole"),
    cover: fe1024img("Mole.png"),
  },
  {
    title: "Monster_Maker",
    name: "Monster_Maker",
    url: fe1024("Monster_Maker"),
    cover: fe1024img("Monster_Maker.png"),
  },
  {
    title: "Morse_Code_Generator",
    name: "Morse_Code_Generator",
    url: fe1024("Morse_Code_Generator"),
    cover: fe1024img("Morse_Code_Generator.png"),
  },
  {
    title: "Movie_Guessing_Game",
    name: "Movie_Guessing_Game",
    url: fe1024("Movie_Guessing_Game"),
    cover: fe1024img("Movie_Guessing_Game.png"),
  },
  {
    title: "MrFakeGame",
    name: "MrFakeGame",
    url: fe1024("MrFakeGame"),
    cover: fe1024img("MrFakeGame.png"),
  },
  {
    title: "Multiplayer_Shooting_Game",
    name: "Multiplayer_Shooting_Game",
    url: fe1024("Multiplayer_Shooting_Game"),
    cover: fe1024img("Multiplayer_Shooting_Game.png"),
  },
  {
    title: "Music_Guess_Game",
    name: "Music_Guess_Game",
    url: fe1024("Music_Guess_Game"),
    cover: fe1024img("Music_Guess_Game.png"),
  },
  {
    title: "Musical_Floor",
    name: "Musical_Floor",
    url: fe1024("Musical_Floor"),
    cover: fe1024img("Musical_Floor.png"),
  },
  {
    title: "Musical_Memory",
    name: "Musical_Memory",
    url: fe1024("Musical_Memory"),
    cover: fe1024img("Musical_Memory.png"),
  },
  {
    title: "NewsJunction",
    name: "NewsJunction",
    url: fe1024("NewsJunction"),
    cover: fe1024img("NewsJunction.png"),
  },
  {
    title: "Ninja_Hattori_Game",
    name: "Ninja_Hattori_Game",
    url: fe1024("Ninja_Hattori_Game"),
    cover: fe1024img("Ninja_Hattori_Game.png"),
  },
  {
    title: "Norman_The_Necromancer",
    name: "Norman_The_Necromancer",
    url: fe1024("Norman_The_Necromancer"),
    cover: fe1024img("Norman_The_Necromancer.png"),
  },
  {
    title: "Not_morethan5",
    name: "Not_morethan5",
    url: fe1024("Not_morethan5"),
    cover: fe1024img("Not_morethan5.png"),
  },
  {
    title: "Noughts_And_Crosses",
    name: "Noughts_And_Crosses",
    url: fe1024("Noughts_And_Crosses"),
    cover: fe1024img("Noughts_And_Crosses.png"),
  },
  {
    title: "Number Guessing Game",
    name: "Number Guessing Game",
    url: fe1024("Number Guessing Game"),
    cover: fe1024img("Number Guessing Game.png"),
  },
  {
    title: "Number_Catcher_Game",
    name: "Number_Catcher_Game",
    url: fe1024("Number_Catcher_Game"),
    cover: fe1024img("Number_Catcher_Game.png"),
  },
  {
    title: "Number_Guessing_Game",
    name: "Number_Guessing_Game",
    url: fe1024("Number_Guessing_Game"),
    cover: fe1024img("Number_Guessing_Game.png"),
  },
  {
    title: "Number_Recall_Game",
    name: "Number_Recall_Game",
    url: fe1024("Number_Recall_Game"),
    cover: fe1024img("Number_Recall_Game.png"),
  },
  {
    title: "Number_Sliding_Puzzle_Game",
    name: "Number_Sliding_Puzzle_Game",
    url: fe1024("Number_Sliding_Puzzle_Game"),
    cover: fe1024img("Number_Sliding_Puzzle_Game.png"),
  },
  {
    title: "Number_Sorting_Game",
    name: "Number_Sorting_Game",
    url: fe1024("Number_Sorting_Game"),
    cover: fe1024img("Number_Sorting_Game.png"),
  },
];
