import { fe1024, fe1024img } from "../helper";

export default () => [
  {
    title: "Observe_the_Cloud",
    name: "Observe_the_Cloud",
    url: fe1024("Observe_the_Cloud"),
    cover: fe1024img("Observe_the_Cloud.png"),
  },
  {
    title: "Othello",
    name: "Othello",
    url: fe1024("Othello"),
    cover: fe1024img("Othello.png"),
  },
  {
    title: "Otherworldly_Odyssey",
    name: "Otherworldly_Odyssey",
    url: fe1024("Otherworldly_Odyssey"),
    cover: fe1024img("Otherworldly_Odyssey.png"),
  },
  {
    title: "OutRun_Offline_Game",
    name: "OutRun_Offline_Game",
    url: fe1024("OutRun_Offline_Game"),
    cover: fe1024img("OutRun_Offline_Game.png"),
  },
  {
    title: "Pac_Man",
    name: "Pac_Man",
    url: fe1024("Pac_Man"),
    cover: fe1024img("Pac_Man.png"),
  },
  {
    title: "Pac_Man_Game",
    name: "Pac_Man_Game",
    url: fe1024("Pac_Man_Game"),
    cover: fe1024img("Pac_Man_Game.png"),
  },
  {
    title: "Pacific_Air_Battle",
    name: "Pacific_Air_Battle",
    url: fe1024("Pacific_Air_Battle"),
    cover: fe1024img("Pacific_Air_Battle.png"),
  },
  {
    title: "Packabunchas",
    name: "Packabunchas",
    url: fe1024("Packabunchas"),
    cover: fe1024img("Packabunchas.png"),
  },
  {
    title: "Painting_Game",
    name: "Painting_Game",
    url: fe1024("Painting_Game"),
    cover: fe1024img("Painting_Game.png"),
  },
  {
    title: "Path_Finder_Challenge",
    name: "Path_Finder_Challenge",
    url: fe1024("Path_Finder_Challenge"),
    cover: fe1024img("Path_Finder_Challenge.png"),
  },
  {
    title: "Pathplex",
    name: "Pathplex",
    url: fe1024("Pathplex"),
    cover: fe1024img("Pathplex.png"),
  },
  {
    title: "Pattern_Creation_Game",
    name: "Pattern_Creation_Game",
    url: fe1024("Pattern_Creation_Game"),
    cover: fe1024img("Pattern_Creation_Game.png"),
  },
  {
    title: "PenPointerFight",
    name: "PenPointerFight",
    url: fe1024("PenPointerFight"),
    cover: fe1024img("PenPointerFight.png"),
  },
  {
    title: "Penalty_Shootout_Game",
    name: "Penalty_Shootout_Game",
    url: fe1024("Penalty_Shootout_Game"),
    cover: fe1024img("Penalty_Shootout_Game.png"),
  },
  {
    title: "Penguins_Can't_Fly",
    name: "Penguins_Can't_Fly",
    url: fe1024("Penguins_Can't_Fly"),
    cover: fe1024img("Penguins_Can't_Fly.png"),
  },
  {
    title: "Physics_Quizz",
    name: "Physics_Quizz",
    url: fe1024("Physics_Quizz"),
    cover: fe1024img("Physics_Quizz.png"),
  },
  {
    title: "Piano",
    name: "Piano",
    url: fe1024("Piano"),
    cover: fe1024img("Piano.png"),
  },
  {
    title: "PianoTiles_Game",
    name: "PianoTiles_Game",
    url: fe1024("PianoTiles_Game"),
    cover: fe1024img("PianoTiles_Game.png"),
  },
  {
    title: "Pictionary_Game",
    name: "Pictionary_Game",
    url: fe1024("Pictionary_Game"),
    cover: fe1024img("Pictionary_Game.png"),
  },
  {
    title: "Pig_game",
    name: "Pig_game",
    url: fe1024("Pig_game"),
    cover: fe1024img("Pig_game.png"),
  },
  {
    title: "Pikachu_Volleyball",
    name: "Pikachu_Volleyball",
    url: fe1024("Pikachu_Volleyball"),
    cover: fe1024img("Pikachu_Volleyball.png"),
  },
  {
    title: "Pinball",
    name: "Pinball",
    url: fe1024("Pinball"),
    cover: fe1024img("Pinball.png"),
  },
  {
    title: "Ping_Pong",
    name: "Ping_Pong",
    url: fe1024("Ping_Pong"),
    cover: fe1024img("Ping_Pong.png"),
  },
  {
    title: "Ping_Pong_Multiplayer",
    name: "Ping_Pong_Multiplayer",
    url: fe1024("Ping_Pong_Multiplayer"),
    cover: fe1024img("Ping_Pong_Multiplayer.png"),
  },
  {
    title: "Ping_Pong_Singleplayer",
    name: "Ping_Pong_Singleplayer",
    url: fe1024("Ping_Pong_Singleplayer"),
    cover: fe1024img("Ping_Pong_Singleplayer.png"),
  },
  {
    title: "Pixel_Painter",
    name: "Pixel_Painter",
    url: fe1024("Pixel_Painter"),
    cover: fe1024img("Pixel_Painter.png"),
  },
  {
    title: "Pixel_Smash",
    name: "Pixel_Smash",
    url: fe1024("Pixel_Smash"),
    cover: fe1024img("Pixel_Smash.png"),
  },
  {
    title: "Pixels_From_Space",
    name: "Pixels_From_Space",
    url: fe1024("Pixels_From_Space"),
    cover: fe1024img("Pixels_From_Space.png"),
  },
  {
    title: "Planet_Defense",
    name: "Planet_Defense",
    url: fe1024("Planet_Defense"),
    cover: fe1024img("Planet_Defense.png"),
  },
  {
    title: "Planet_Game",
    name: "Planet_Game",
    url: fe1024("Planet_Game"),
    cover: fe1024img("Planet_Game.png"),
  },
  {
    title: "Plankman",
    name: "Plankman",
    url: fe1024("Plankman"),
    cover: fe1024img("Plankman.png"),
  },
  {
    title: "Platform_Game",
    name: "Platform_Game",
    url: fe1024("Platform_Game"),
    cover: fe1024img("Platform_Game.png"),
  },
  {
    title: "Platform_game_engine",
    name: "Platform_game_engine",
    url: fe1024("Platform_game_engine"),
    cover: fe1024img("Platform_game_engine.png"),
  },
  {
    title: "Poke_Guess_Blitz",
    name: "Poke_Guess_Blitz",
    url: fe1024("Poke_Guess_Blitz"),
    cover: fe1024img("Poke_Guess_Blitz.png"),
  },
  {
    title: "Pokedex",
    name: "Pokedex",
    url: fe1024("Pokedex"),
    cover: fe1024img("Pokedex.png"),
  },
  {
    title: "Pokemon_Adventure_Game",
    name: "Pokemon_Adventure_Game",
    url: fe1024("Pokemon_Adventure_Game"),
    cover: fe1024img("Pokemon_Adventure_Game.png"),
  },
  {
    title: "Pokemon_Ball_Finder",
    name: "Pokemon_Ball_Finder",
    url: fe1024("Pokemon_Ball_Finder"),
    cover: fe1024img("Pokemon_Ball_Finder.png"),
  },
  {
    title: "Pokemon_Card_Game",
    name: "Pokemon_Card_Game",
    url: fe1024("Pokemon_Card_Game"),
    cover: fe1024img("Pokemon_Card_Game.png"),
  },
  {
    title: "Pokemon_Stats_Card",
    name: "Pokemon_Stats_Card",
    url: fe1024("Pokemon_Stats_Card"),
    cover: fe1024img("Pokemon_Stats_Card.png"),
  },
  {
    title: "Poker_Dice",
    name: "Poker_Dice",
    url: fe1024("Poker_Dice"),
    cover: fe1024img("Poker_Dice.png"),
  },
  {
    title: "Pong",
    name: "Pong",
    url: fe1024("Pong"),
    cover: fe1024img("Pong.png"),
  },
  {
    title: "Pong_Ball",
    name: "Pong_Ball",
    url: fe1024("Pong_Ball"),
    cover: fe1024img("Pong_Ball.png"),
  },
  {
    title: "Pop_My_Balloon",
    name: "Pop_My_Balloon",
    url: fe1024("Pop_My_Balloon"),
    cover: fe1024img("Pop_My_Balloon.png"),
  },
  {
    title: "Pop_the_Bubbles",
    name: "Pop_the_Bubbles",
    url: fe1024("Pop_the_Bubbles"),
    cover: fe1024img("Pop_the_Bubbles.png"),
  },
  {
    title: "Pottery-Game",
    name: "Pottery-Game",
    url: fe1024("Pottery-Game"),
    cover: fe1024img("Pottery-Game.png"),
  },
  {
    title: "Prime-No-Finder-Game",
    name: "Prime-No-Finder-Game",
    url: fe1024("Prime-No-Finder-Game"),
    cover: fe1024img("Prime-No-Finder-Game.png"),
  },
  {
    title: "Projectile_Motion_Game",
    name: "Projectile_Motion_Game",
    url: fe1024("Projectile_Motion_Game"),
    cover: fe1024img("Projectile_Motion_Game.png"),
  },
  {
    title: "Pumpkin_Pursuit",
    name: "Pumpkin_Pursuit",
    url: fe1024("Pumpkin_Pursuit"),
    cover: fe1024img("Pumpkin_Pursuit.png"),
  },
  {
    title: "Puzzel_winner",
    name: "Puzzel_winner",
    url: fe1024("Puzzel_winner"),
    cover: fe1024img("Puzzel_winner.png"),
  },
  {
    title: "Puzzle_Game",
    name: "Puzzle_Game",
    url: fe1024("Puzzle_Game"),
    cover: fe1024img("Puzzle_Game.png"),
  },
  {
    title: "Quest_For_Riches",
    name: "Quest_For_Riches",
    url: fe1024("Quest_For_Riches"),
    cover: fe1024img("Quest_For_Riches.png"),
  },
  {
    title: "QuickFingers",
    name: "QuickFingers",
    url: fe1024("QuickFingers"),
    cover: fe1024img("QuickFingers.png"),
  },
  {
    title: "Quick_Click",
    name: "Quick_Click",
    url: fe1024("Quick_Click"),
    cover: fe1024img("Quick_Click.png"),
  },
  {
    title: "Quick_Math",
    name: "Quick_Math",
    url: fe1024("Quick_Math"),
    cover: fe1024img("Quick_Math.png"),
  },
  {
    title: "Quiz_With_Timer",
    name: "Quiz_With_Timer",
    url: fe1024("Quiz_With_Timer"),
    cover: fe1024img("Quiz_With_Timer.png"),
  },
  {
    title: "Quiz_it_out",
    name: "Quiz_it_out",
    url: fe1024("Quiz_it_out"),
    cover: fe1024img("Quiz_it_out.png"),
  },
  {
    title: "Quizify",
    name: "Quizify",
    url: fe1024("Quizify"),
    cover: fe1024img("Quizify.png"),
  },
  {
    title: "QuizzApp",
    name: "QuizzApp",
    url: fe1024("QuizzApp"),
    cover: fe1024img("QuizzApp.png"),
  },
  {
    title: "RIP",
    name: "RIP",
    url: fe1024("RIP"),
    cover: fe1024img("RIP.png"),
  },
  {
    title: "Rabbit_Rush",
    name: "Rabbit_Rush",
    url: fe1024("Rabbit_Rush"),
    cover: fe1024img("Rabbit_Rush.png"),
  },
  {
    title: "Random_Advice_Generator",
    name: "Random_Advice_Generator",
    url: fe1024("Random_Advice_Generator"),
    cover: fe1024img("Random_Advice_Generator.png"),
  },
  {
    title: "Random_Choice_Picker",
    name: "Random_Choice_Picker",
    url: fe1024("Random_Choice_Picker"),
    cover: fe1024img("Random_Choice_Picker.png"),
  },
  {
    title: "Random_Joke_Generator",
    name: "Random_Joke_Generator",
    url: fe1024("Random_Joke_Generator"),
    cover: fe1024img("Random_Joke_Generator.png"),
  },
  {
    title: "Reaction_Time",
    name: "Reaction_Time",
    url: fe1024("Reaction_Time"),
    cover: fe1024img("Reaction_Time.png"),
  },
  {
    title: "Recognizing_Figures",
    name: "Recognizing_Figures",
    url: fe1024("Recognizing_Figures"),
    cover: fe1024img("Recognizing_Figures.png"),
  },
  {
    title: "Rectangular",
    name: "Rectangular",
    url: fe1024("Rectangular"),
    cover: fe1024img("Rectangular.png"),
  },
  {
    title: "Red_Light_Green_Light",
    name: "Red_Light_Green_Light",
    url: fe1024("Red_Light_Green_Light"),
    cover: fe1024img("Red_Light_Green_Light.png"),
  },
  {
    title: "Reflex_Game",
    name: "Reflex_Game",
    url: fe1024("Reflex_Game"),
    cover: fe1024img("Reflex_Game.png"),
  },
  {
    title: "Remember_the_color",
    name: "Remember_the_color",
    url: fe1024("Remember_the_color"),
    cover: fe1024img("Remember_the_color.png"),
  },
  {
    title: "Response_Reaction",
    name: "Response_Reaction",
    url: fe1024("Response_Reaction"),
    cover: fe1024img("Response_Reaction.png"),
  },
  {
    title: "Retro_Dungeon_Puzzle",
    name: "Retro_Dungeon_Puzzle",
    url: fe1024("Retro_Dungeon_Puzzle"),
    cover: fe1024img("Retro_Dungeon_Puzzle.png"),
  },
  {
    title: "Reverse Memory",
    name: "Reverse Memory",
    url: fe1024("Reverse Memory"),
    cover: fe1024img("Reverse Memory.png"),
  },
  {
    title: "Reversi",
    name: "Reversi",
    url: fe1024("Reversi"),
    cover: fe1024img("Reversi.png"),
  },
  {
    title: "Riddle_Room",
    name: "Riddle_Room",
    url: fe1024("Riddle_Room"),
    cover: fe1024img("Riddle_Room.png"),
  },
  {
    title: "Riddle_game",
    name: "Riddle_game",
    url: fe1024("Riddle_game"),
    cover: fe1024img("Riddle_game.png"),
  },
  {
    title: "Risky_Nav",
    name: "Risky_Nav",
    url: fe1024("Risky_Nav"),
    cover: fe1024img("Risky_Nav.png"),
  },
  {
    title: "RoadFighter",
    name: "RoadFighter",
    url: fe1024("RoadFighter"),
    cover: fe1024img("RoadFighter.png"),
  },
  {
    title: "Rock-Paper",
    name: "Rock-Paper",
    url: fe1024("Rock-Paper"),
    cover: fe1024img("Rock-Paper.png"),
  },
  {
    title: "Rock_Paper_Scissors",
    name: "Rock_Paper_Scissors",
    url: fe1024("Rock_Paper_Scissors"),
    cover: fe1024img("Rock_Paper_Scissors.png"),
  },
  {
    title: "Rock_Paper_Scissors_Lizard_Spock",
    name: "Rock_Paper_Scissors_Lizard_Spock",
    url: fe1024("Rock_Paper_Scissors_Lizard_Spock"),
    cover: fe1024img("Rock_Paper_Scissors_Lizard_Spock.png"),
  },
  {
    title: "Rock_Paper_Scissors_Lizard_Spock_Game",
    name: "Rock_Paper_Scissors_Lizard_Spock_Game",
    url: fe1024("Rock_Paper_Scissors_Lizard_Spock_Game"),
    cover: fe1024img("Rock_Paper_Scissors_Lizard_Spock_Game.png"),
  },
  {
    title: "Rock_Paper_Scissors_Neon",
    name: "Rock_Paper_Scissors_Neon",
    url: fe1024("Rock_Paper_Scissors_Neon"),
    cover: fe1024img("Rock_Paper_Scissors_Neon.png"),
  },
  {
    title: "Rock_paper_scissor",
    name: "Rock_paper_scissor",
    url: fe1024("Rock_paper_scissor"),
    cover: fe1024img("Rock_paper_scissor.png"),
  },
  {
    title: "Rocket_Ride",
    name: "Rocket_Ride",
    url: fe1024("Rocket_Ride"),
    cover: fe1024img("Rocket_Ride.png"),
  },
  {
    title: "Rocket_Shooter",
    name: "Rocket_Shooter",
    url: fe1024("Rocket_Shooter"),
    cover: fe1024img("Rocket_Shooter.png"),
  },
  {
    title: "Rocket_Showdown",
    name: "Rocket_Showdown",
    url: fe1024("Rocket_Showdown"),
    cover: fe1024img("Rocket_Showdown.png"),
  },
  {
    title: "Roll_Race",
    name: "Roll_Race",
    url: fe1024("Roll_Race"),
    cover: fe1024img("Roll_Race.png"),
  },
  {
    title: "Roll_The_Dice",
    name: "Roll_The_Dice",
    url: fe1024("Roll_The_Dice"),
    cover: fe1024img("Roll_The_Dice.png"),
  },
  {
    title: "Rotating_Elements",
    name: "Rotating_Elements",
    url: fe1024("Rotating_Elements"),
    cover: fe1024img("Rotating_Elements.png"),
  },
  {
    title: "Roulette",
    name: "Roulette",
    url: fe1024("Roulette"),
    cover: fe1024img("Roulette.png"),
  },
  {
    title: "Rubik's_solver",
    name: "Rubik's_solver",
    url: fe1024("Rubik's_solver"),
    cover: fe1024img("Rubik's_solver.png"),
  },
  {
    title: "Run and Jump",
    name: "Run and Jump",
    url: fe1024("Run and Jump"),
    cover: fe1024img("Run and Jump.png"),
  },
  {
    title: "Run_Dora_Run",
    name: "Run_Dora_Run",
    url: fe1024("Run_Dora_Run"),
    cover: fe1024img("Run_Dora_Run.png"),
  },
  {
    title: "Samurai_Fighting_Game",
    name: "Samurai_Fighting_Game",
    url: fe1024("Samurai_Fighting_Game"),
    cover: fe1024img("Samurai_Fighting_Game.png"),
  },
  {
    title: "Save_Doraemon",
    name: "Save_Doraemon",
    url: fe1024("Save_Doraemon"),
    cover: fe1024img("Save_Doraemon.png"),
  },
  {
    title: "Save_Princess",
    name: "Save_Princess",
    url: fe1024("Save_Princess"),
    cover: fe1024img("Save_Princess.png"),
  },
  {
    title: "Save_The_Forest",
    name: "Save_The_Forest",
    url: fe1024("Save_The_Forest"),
    cover: fe1024img("Save_The_Forest.png"),
  },
  {
    title: "SciFi_Alchemy",
    name: "SciFi_Alchemy",
    url: fe1024("SciFi_Alchemy"),
    cover: fe1024img("SciFi_Alchemy.png"),
  },
  {
    title: "Sciarra_Of_Colors",
    name: "Sciarra_Of_Colors",
    url: fe1024("Sciarra_Of_Colors"),
    cover: fe1024img("Sciarra_Of_Colors.png"),
  },
  {
    title: "Screen_Pet_Game",
    name: "Screen_Pet_Game",
    url: fe1024("Screen_Pet_Game"),
    cover: fe1024img("Screen_Pet_Game.png"),
  },
  {
    title: "Scribble",
    name: "Scribble",
    url: fe1024("Scribble"),
    cover: fe1024img("Scribble.png"),
  },
  {
    title: "Sentence_Scramble",
    name: "Sentence_Scramble",
    url: fe1024("Sentence_Scramble"),
    cover: fe1024img("Sentence_Scramble.png"),
  },
  {
    title: "Shadow_PokeGuess",
    name: "Shadow_PokeGuess",
    url: fe1024("Shadow_PokeGuess"),
    cover: fe1024img("Shadow_PokeGuess.png"),
  },
  {
    title: "Shadow_Runner",
    name: "Shadow_Runner",
    url: fe1024("Shadow_Runner"),
    cover: fe1024img("Shadow_Runner.png"),
  },
  {
    title: "Shape Finder",
    name: "Shape Finder",
    url: fe1024("Shape Finder"),
    cover: fe1024img("Shape Finder.png"),
  },
  {
    title: "Shape_Blocks",
    name: "Shape_Blocks",
    url: fe1024("Shape_Blocks"),
    cover: fe1024img("Shape_Blocks.png"),
  },
  {
    title: "Shell_Game",
    name: "Shell_Game",
    url: fe1024("Shell_Game"),
    cover: fe1024img("Shell_Game.png"),
  },
  {
    title: "Shoot_Duck_Game",
    name: "Shoot_Duck_Game",
    url: fe1024("Shoot_Duck_Game"),
    cover: fe1024img("Shoot_Duck_Game.png"),
  },
  {
    title: "Shoot_The_Balloon",
    name: "Shoot_The_Balloon",
    url: fe1024("Shoot_The_Balloon"),
    cover: fe1024img("Shoot_The_Balloon.png"),
  },
  {
    title: "Short_Circuit",
    name: "Short_Circuit",
    url: fe1024("Short_Circuit"),
    cover: fe1024img("Short_Circuit.png"),
  },
  {
    title: "Shpere",
    name: "Shpere",
    url: fe1024("Shpere"),
    cover: fe1024img("Shpere.png"),
  },
  {
    title: "Shrek_Vs_Wild",
    name: "Shrek_Vs_Wild",
    url: fe1024("Shrek_Vs_Wild"),
    cover: fe1024img("Shrek_Vs_Wild.png"),
  },
  {
    title: "ShroomKnight",
    name: "ShroomKnight",
    url: fe1024("ShroomKnight"),
    cover: fe1024img("ShroomKnight.png"),
  },
  {
    title: "Simon_Game_Challenge",
    name: "Simon_Game_Challenge",
    url: fe1024("Simon_Game_Challenge"),
    cover: fe1024img("Simon_Game_Challenge.png"),
  },
  {
    title: "Simon_Says",
    name: "Simon_Says",
    url: fe1024("Simon_Says"),
    cover: fe1024img("Simon_Says.png"),
  },
  {
    title: "Single_Player_Solitaire",
    name: "Single_Player_Solitaire",
    url: fe1024("Single_Player_Solitaire"),
    cover: fe1024img("Single_Player_Solitaire.png"),
  },
  {
    title: "Skeleathon",
    name: "Skeleathon",
    url: fe1024("Skeleathon"),
    cover: fe1024img("Skeleathon.png"),
  },
  {
    title: "Sky_Dodge",
    name: "Sky_Dodge",
    url: fe1024("Sky_Dodge"),
    cover: fe1024img("Sky_Dodge.png"),
  },
  {
    title: "Sky_Jumper",
    name: "Sky_Jumper",
    url: fe1024("Sky_Jumper"),
    cover: fe1024img("Sky_Jumper.png"),
  },
  {
    title: "Sky_Lift_Dash",
    name: "Sky_Lift_Dash",
    url: fe1024("Sky_Lift_Dash"),
    cover: fe1024img("Sky_Lift_Dash.png"),
  },
  {
    title: "Slice_Storm",
    name: "Slice_Storm",
    url: fe1024("Slice_Storm"),
    cover: fe1024img("Slice_Storm.png"),
  },
  {
    title: "Slide_Master_Puzzle",
    name: "Slide_Master_Puzzle",
    url: fe1024("Slide_Master_Puzzle"),
    cover: fe1024img("Slide_Master_Puzzle.png"),
  },
  {
    title: "Slide_Puzzle",
    name: "Slide_Puzzle",
    url: fe1024("Slide_Puzzle"),
    cover: fe1024img("Slide_Puzzle.png"),
  },
  {
    title: "Sliding_puzzle",
    name: "Sliding_puzzle",
    url: fe1024("Sliding_puzzle"),
    cover: fe1024img("Sliding_puzzle.png"),
  },
  {
    title: "Slime_attack_game",
    name: "Slime_attack_game",
    url: fe1024("Slime_attack_game"),
    cover: fe1024img("Slime_attack_game.png"),
  },
  {
    title: "Smash-Monty-mole-master-main",
    name: "Smash-Monty-mole-master-main",
    url: fe1024("Smash-Monty-mole-master-main"),
    cover: fe1024img("Smash-Monty-mole-master-main.png"),
  },
  {
    title: "Smashing_Blocks",
    name: "Smashing_Blocks",
    url: fe1024("Smashing_Blocks"),
    cover: fe1024img("Smashing_Blocks.png"),
  },
  {
    title: "Snail_Game",
    name: "Snail_Game",
    url: fe1024("Snail_Game"),
    cover: fe1024img("Snail_Game.png"),
  },
  {
    title: "SnakeBites",
    name: "SnakeBites",
    url: fe1024("SnakeBites"),
    cover: fe1024img("SnakeBites.png"),
  },
  {
    title: "Snake_Feeder_Game",
    name: "Snake_Feeder_Game",
    url: fe1024("Snake_Feeder_Game"),
    cover: fe1024img("Snake_Feeder_Game.png"),
  },
  {
    title: "Snake_Game",
    name: "Snake_Game",
    url: fe1024("Snake_Game"),
    cover: fe1024img("Snake_Game.png"),
  },
  {
    title: "Snake_Gun_Water",
    name: "Snake_Gun_Water",
    url: fe1024("Snake_Gun_Water"),
    cover: fe1024img("Snake_Gun_Water.png"),
  },
  {
    title: "Snake_Ladder",
    name: "Snake_Ladder",
    url: fe1024("Snake_Ladder"),
    cover: fe1024img("Snake_Ladder.png"),
  },
  {
    title: "Snooze",
    name: "Snooze",
    url: fe1024("Snooze"),
    cover: fe1024img("Snooze.png"),
  },
  {
    title: "Soccer",
    name: "Soccer",
    url: fe1024("Soccer"),
    cover: fe1024img("Soccer.png"),
  },
  {
    title: "Solitaire",
    name: "Solitaire",
    url: fe1024("Solitaire"),
    cover: fe1024img("Solitaire.png"),
  },
  {
    title: "Solitaire_up",
    name: "Solitaire_up",
    url: fe1024("Solitaire_up"),
    cover: fe1024img("Solitaire_up.png"),
  },
  {
    title: "Sonic_The_Hedgehog",
    name: "Sonic_The_Hedgehog",
    url: fe1024("Sonic_The_Hedgehog"),
    cover: fe1024img("Sonic_The_Hedgehog.png"),
  },
  {
    title: "Sorades",
    name: "Sorades",
    url: fe1024("Sorades"),
    cover: fe1024img("Sorades.png"),
  },
  {
    title: "Soul_Jumper",
    name: "Soul_Jumper",
    url: fe1024("Soul_Jumper"),
    cover: fe1024img("Soul_Jumper.png"),
  },
  {
    title: "Space_Dash",
    name: "Space_Dash",
    url: fe1024("Space_Dash"),
    cover: fe1024img("Space_Dash.png"),
  },
  {
    title: "Space_Defence",
    name: "Space_Defence",
    url: fe1024("Space_Defence"),
    cover: fe1024img("Space_Defence.png"),
  },
  {
    title: "Space_Dominators",
    name: "Space_Dominators",
    url: fe1024("Space_Dominators"),
    cover: fe1024img("Space_Dominators.png"),
  },
  {
    title: "Space_Exploration",
    name: "Space_Exploration",
    url: fe1024("Space_Exploration"),
    cover: fe1024img("Space_Exploration.png"),
  },
  {
    title: "Space_Gun",
    name: "Space_Gun",
    url: fe1024("Space_Gun"),
    cover: fe1024img("Space_Gun.png"),
  },
  {
    title: "Space_Huggers",
    name: "Space_Huggers",
    url: fe1024("Space_Huggers"),
    cover: fe1024img("Space_Huggers.png"),
  },
  {
    title: "Space_Invaders",
    name: "Space_Invaders",
    url: fe1024("Space_Invaders"),
    cover: fe1024img("Space_Invaders.png"),
  },
  {
    title: "Space_War",
    name: "Space_War",
    url: fe1024("Space_War"),
    cover: fe1024img("Space_War.png"),
  },
  {
    title: "Spaceducts",
    name: "Spaceducts",
    url: fe1024("Spaceducts"),
    cover: fe1024img("Spaceducts.png"),
  },
  {
    title: "Spacepi",
    name: "Spacepi",
    url: fe1024("Spacepi"),
    cover: fe1024img("Spacepi.png"),
  },
  {
    title: "Spaceship_Escort",
    name: "Spaceship_Escort",
    url: fe1024("Spaceship_Escort"),
    cover: fe1024img("Spaceship_Escort.png"),
  },
  {
    title: "Spell_Bee",
    name: "Spell_Bee",
    url: fe1024("Spell_Bee"),
    cover: fe1024img("Spell_Bee.png"),
  },
  {
    title: "Spelling_Bee",
    name: "Spelling_Bee",
    url: fe1024("Spelling_Bee"),
    cover: fe1024img("Spelling_Bee.png"),
  },
  {
    title: "Spider_Man_Go",
    name: "Spider_Man_Go",
    url: fe1024("Spider_Man_Go"),
    cover: fe1024img("Spider_Man_Go.png"),
  },
  {
    title: "Spin_the_wheel",
    name: "Spin_the_wheel",
    url: fe1024("Spin_the_wheel"),
    cover: fe1024img("Spin_the_wheel.png"),
  },
  {
    title: "Spirograph",
    name: "Spirograph",
    url: fe1024("Spirograph"),
    cover: fe1024img("Spirograph.png"),
  },
  {
    title: "Squared_lines",
    name: "Squared_lines",
    url: fe1024("Squared_lines"),
    cover: fe1024img("Squared_lines.png"),
  },
  {
    title: "Squashing_your_Enemy",
    name: "Squashing_your_Enemy",
    url: fe1024("Squashing_your_Enemy"),
    cover: fe1024img("Squashing_your_Enemy.png"),
  },
  {
    title: "Squid_Game",
    name: "Squid_Game",
    url: fe1024("Squid_Game"),
    cover: fe1024img("Squid_Game.png"),
  },
  {
    title: "Stack_Game",
    name: "Stack_Game",
    url: fe1024("Stack_Game"),
    cover: fe1024img("Stack_Game.png"),
  },
  {
    title: "Star_Trek_Trivia",
    name: "Star_Trek_Trivia",
    url: fe1024("Star_Trek_Trivia"),
    cover: fe1024img("Star_Trek_Trivia.png"),
  },
  {
    title: "Steam_Punk",
    name: "Steam_Punk",
    url: fe1024("Steam_Punk"),
    cover: fe1024img("Steam_Punk.png"),
  },
  {
    title: "Steampunk_FlappyBird",
    name: "Steampunk_FlappyBird",
    url: fe1024("Steampunk_FlappyBird"),
    cover: fe1024img("Steampunk_FlappyBird.png"),
  },
  {
    title: "StickTheSticker",
    name: "StickTheSticker",
    url: fe1024("StickTheSticker"),
    cover: fe1024img("StickTheSticker.png"),
  },
  {
    title: "Stick_Hero_Game",
    name: "Stick_Hero_Game",
    url: fe1024("Stick_Hero_Game"),
    cover: fe1024img("Stick_Hero_Game.png"),
  },
  {
    title: "Stolen_Sword",
    name: "Stolen_Sword",
    url: fe1024("Stolen_Sword"),
    cover: fe1024img("Stolen_Sword.png"),
  },
  {
    title: "Stone_paper_scissor",
    name: "Stone_paper_scissor",
    url: fe1024("Stone_paper_scissor"),
    cover: fe1024img("Stone_paper_scissor.png"),
  },
  {
    title: "Subway_Surfers",
    name: "Subway_Surfers",
    url: fe1024("Subway_Surfers"),
    cover: fe1024img("Subway_Surfers.png"),
  },
  {
    title: "Sucker",
    name: "Sucker",
    url: fe1024("Sucker"),
    cover: fe1024img("Sucker.png"),
  },
  {
    title: "Sudoku",
    name: "Sudoku",
    url: fe1024("Sudoku"),
    cover: fe1024img("Sudoku.png"),
  },
  {
    title: "Sudoku_light_theme",
    name: "Sudoku_light_theme",
    url: fe1024("Sudoku_light_theme"),
    cover: fe1024img("Sudoku_light_theme.png"),
  },
  {
    title: "Super_mario_run",
    name: "Super_mario_run",
    url: fe1024("Super_mario_run"),
    cover: fe1024img("Super_mario_run.png"),
  },
  {
    title: "Super_tetris",
    name: "Super_tetris",
    url: fe1024("Super_tetris"),
    cover: fe1024img("Super_tetris.png"),
  },
  {
    title: "Swap-Card-Game",
    name: "Swap-Card-Game",
    url: fe1024("Swap-Card-Game"),
    cover: fe1024img("Swap-Card-Game.png"),
  },
  {
    title: "Swift",
    name: "Swift",
    url: fe1024("Swift"),
    cover: fe1024img("Swift.png"),
  },
  {
    title: "Synonym-Typing-Game",
    name: "Synonym-Typing-Game",
    url: fe1024("Synonym-Typing-Game"),
    cover: fe1024img("Synonym-Typing-Game.png"),
  },
  {
    title: "Synonym_Symphony",
    name: "Synonym_Symphony",
    url: fe1024("Synonym_Symphony"),
    cover: fe1024img("Synonym_Symphony.png"),
  },
  {
    title: "Taash Game",
    name: "Taash Game",
    url: fe1024("Taash Game"),
    cover: fe1024img("Taash Game.png"),
  },
  {
    title: "Target_Torrent",
    name: "Target_Torrent",
    url: fe1024("Target_Torrent"),
    cover: fe1024img("Target_Torrent.png"),
  },
  {
    title: "Tech_Memory_Block",
    name: "Tech_Memory_Block",
    url: fe1024("Tech_Memory_Block"),
    cover: fe1024img("Tech_Memory_Block.png"),
  },
  {
    title: "Technical_Mind_Game",
    name: "Technical_Mind_Game",
    url: fe1024("Technical_Mind_Game"),
    cover: fe1024img("Technical_Mind_Game.png"),
  },
  {
    title: "Tenacity",
    name: "Tenacity",
    url: fe1024("Tenacity"),
    cover: fe1024img("Tenacity.png"),
  },
  {
    title: "Tennis",
    name: "Tennis",
    url: fe1024("Tennis"),
    cover: fe1024img("Tennis.png"),
  },
  {
    title: "Tenzies",
    name: "Tenzies",
    url: fe1024("Tenzies"),
    cover: fe1024img("Tenzies.png"),
  },
  {
    title: "Terror_Seventy",
    name: "Terror_Seventy",
    url: fe1024("Terror_Seventy"),
    cover: fe1024img("Terror_Seventy.png"),
  },
  {
    title: "Tether",
    name: "Tether",
    url: fe1024("Tether"),
    cover: fe1024img("Tether.png"),
  },
  {
    title: "Tetris",
    name: "Tetris",
    url: fe1024("Tetris"),
    cover: fe1024img("Tetris.png"),
  },
  {
    title: "Tetris_Game",
    name: "Tetris_Game",
    url: fe1024("Tetris_Game"),
    cover: fe1024img("Tetris_Game.png"),
  },
  {
    title: "The_Last_Spartan",
    name: "The_Last_Spartan",
    url: fe1024("The_Last_Spartan"),
    cover: fe1024img("The_Last_Spartan.png"),
  },
  {
    title: "The_Mystery_Adventure_Game",
    name: "The_Mystery_Adventure_Game",
    url: fe1024("The_Mystery_Adventure_Game"),
    cover: fe1024img("The_Mystery_Adventure_Game.png"),
  },
  {
    title: "The_Raising_Fighting_Spirits",
    name: "The_Raising_Fighting_Spirits",
    url: fe1024("The_Raising_Fighting_Spirits"),
    cover: fe1024img("The_Raising_Fighting_Spirits.png"),
  },
  {
    title: "The_labyrinth_of_death",
    name: "The_labyrinth_of_death",
    url: fe1024("The_labyrinth_of_death"),
    cover: fe1024img("The_labyrinth_of_death.png"),
  },
  {
    title: "Thirteen",
    name: "Thirteen",
    url: fe1024("Thirteen"),
    cover: fe1024img("Thirteen.png"),
  },
  {
    title: "Tic-Tac-Toe Game",
    name: "Tic-Tac-Toe Game",
    url: fe1024("Tic-Tac-Toe Game"),
    cover: fe1024img("Tic-Tac-Toe Game.png"),
  },
  {
    title: "Tic-tac-toe",
    name: "Tic-tac-toe",
    url: fe1024("Tic-tac-toe"),
    cover: fe1024img("Tic-tac-toe.png"),
  },
  {
    title: "Tic_Tac_Toe",
    name: "Tic_Tac_Toe",
    url: fe1024("Tic_Tac_Toe"),
    cover: fe1024img("Tic_Tac_Toe.png"),
  },
  {
    title: "Tic_Tac_Toe_Game",
    name: "Tic_Tac_Toe_Game",
    url: fe1024("Tic_Tac_Toe_Game"),
    cover: fe1024img("Tic_Tac_Toe_Game.png"),
  },
  {
    title: "Tic_Tac_Toe_Neon",
    name: "Tic_Tac_Toe_Neon",
    url: fe1024("Tic_Tac_Toe_Neon"),
    cover: fe1024img("Tic_Tac_Toe_Neon.png"),
  },
  {
    title: "Tic_tac_toe_responsive",
    name: "Tic_tac_toe_responsive",
    url: fe1024("Tic_tac_toe_responsive"),
    cover: fe1024img("Tic_tac_toe_responsive.png"),
  },
  {
    title: "Tile_Game",
    name: "Tile_Game",
    url: fe1024("Tile_Game"),
    cover: fe1024img("Tile_Game.png"),
  },
  {
    title: "Tilting_Maze",
    name: "Tilting_Maze",
    url: fe1024("Tilting_Maze"),
    cover: fe1024img("Tilting_Maze.png"),
  },
  {
    title: "Timber_Terry",
    name: "Timber_Terry",
    url: fe1024("Timber_Terry"),
    cover: fe1024img("Timber_Terry.png"),
  },
  {
    title: "Tinker_jump_master",
    name: "Tinker_jump_master",
    url: fe1024("Tinker_jump_master"),
    cover: fe1024img("Tinker_jump_master.png"),
  },
  {
    title: "Tiny-Fishing",
    name: "Tiny-Fishing",
    url: fe1024("Tiny-Fishing"),
    cover: fe1024img("Tiny-Fishing.png"),
  },
  {
    title: "Touch-No-Fire-Game",
    name: "Touch-No-Fire-Game",
    url: fe1024("Touch-No-Fire-Game"),
    cover: fe1024img("Touch-No-Fire-Game.png"),
  },
  {
    title: "Touch_The_Ball",
    name: "Touch_The_Ball",
    url: fe1024("Touch_The_Ball"),
    cover: fe1024img("Touch_The_Ball.png"),
  },
  {
    title: "Tower_Block_Game",
    name: "Tower_Block_Game",
    url: fe1024("Tower_Block_Game"),
    cover: fe1024img("Tower_Block_Game.png"),
  },
  {
    title: "Tower_Blocks",
    name: "Tower_Blocks",
    url: fe1024("Tower_Blocks"),
    cover: fe1024img("Tower_Blocks.png"),
  },
  {
    title: "Tower_Building_Game",
    name: "Tower_Building_Game",
    url: fe1024("Tower_Building_Game"),
    cover: fe1024img("Tower_Building_Game.png"),
  },
  {
    title: "Tower_Defence_Game",
    name: "Tower_Defence_Game",
    url: fe1024("Tower_Defence_Game"),
    cover: fe1024img("Tower_Defence_Game.png"),
  },
  {
    title: "Tower_Defense",
    name: "Tower_Defense",
    url: fe1024("Tower_Defense"),
    cover: fe1024img("Tower_Defense.png"),
  },
  {
    title: "Tower_Of_Hanoi",
    name: "Tower_Of_Hanoi",
    url: fe1024("Tower_Of_Hanoi"),
    cover: fe1024img("Tower_Of_Hanoi.png"),
  },
  {
    title: "Tower_Stack",
    name: "Tower_Stack",
    url: fe1024("Tower_Stack"),
    cover: fe1024img("Tower_Stack.png"),
  },
  {
    title: "Town_Rise_Game",
    name: "Town_Rise_Game",
    url: fe1024("Town_Rise_Game"),
    cover: fe1024img("Town_Rise_Game.png"),
  },
  {
    title: "Track_Not_Found",
    name: "Track_Not_Found",
    url: fe1024("Track_Not_Found"),
    cover: fe1024img("Track_Not_Found.png"),
  },
  {
    title: "Traffic_Run",
    name: "Traffic_Run",
    url: fe1024("Traffic_Run"),
    cover: fe1024img("Traffic_Run.png"),
  },
  {
    title: "Trashem",
    name: "Trashem",
    url: fe1024("Trashem"),
    cover: fe1024img("Trashem.png"),
  },
  {
    title: "Treasure Hunt",
    name: "Treasure Hunt",
    url: fe1024("Treasure Hunt"),
    cover: fe1024img("Treasure Hunt.png"),
  },
  {
    title: "Trex_Run",
    name: "Trex_Run",
    url: fe1024("Trex_Run"),
    cover: fe1024img("Trex_Run.png"),
  },
  {
    title: "TriHand_Tactics",
    name: "TriHand_Tactics",
    url: fe1024("TriHand_Tactics"),
    cover: fe1024img("TriHand_Tactics.png"),
  },
  {
    title: "Triangle_Back_To_Home",
    name: "Triangle_Back_To_Home",
    url: fe1024("Triangle_Back_To_Home"),
    cover: fe1024img("Triangle_Back_To_Home.png"),
  },
  {
    title: "Trio_Match",
    name: "Trio_Match",
    url: fe1024("Trio_Match"),
    cover: fe1024img("Trio_Match.png"),
  },
  {
    title: "Trivia_Card",
    name: "Trivia_Card",
    url: fe1024("Trivia_Card"),
    cover: fe1024img("Trivia_Card.png"),
  },
  {
    title: "Trivia_It",
    name: "Trivia_It",
    url: fe1024("Trivia_It"),
    cover: fe1024img("Trivia_It.png"),
  },
  {
    title: "Truth_And_Dare",
    name: "Truth_And_Dare",
    url: fe1024("Truth_And_Dare"),
    cover: fe1024img("Truth_And_Dare.png"),
  },
  {
    title: "Turn_on_the_light",
    name: "Turn_on_the_light",
    url: fe1024("Turn_on_the_light"),
    cover: fe1024img("Turn_on_the_light.png"),
  },
  {
    title: "Typing_Game",
    name: "Typing_Game",
    url: fe1024("Typing_Game"),
    cover: fe1024img("Typing_Game.png"),
  },
  {
    title: "Typing_Speed_Test2",
    name: "Typing_Speed_Test2",
    url: fe1024("Typing_Speed_Test2"),
    cover: fe1024img("Typing_Speed_Test2.png"),
  },
  {
    title: "Typing_Speed_Test_Game",
    name: "Typing_Speed_Test_Game",
    url: fe1024("Typing_Speed_Test_Game"),
    cover: fe1024img("Typing_Speed_Test_Game.png"),
  },
  {
    title: "Typing_Test",
    name: "Typing_Test",
    url: fe1024("Typing_Test"),
    cover: fe1024img("Typing_Test.png"),
  },
];
