import { fe1024, fe1024img } from "../helper";

export default () => [
  {
    title: "UNO",
    name: "UNO",
    url: fe1024("UNO"),
    cover: fe1024img("UNO.png"),
  },
  {
    title: "UNO_game_with_Computer",
    name: "UNO_game_with_Computer",
    url: fe1024("UNO_game_with_Computer"),
    cover: fe1024img("UNO_game_with_Computer.png"),
  },
  {
    title: "Ultimate_Football_Manager",
    name: "Ultimate_Football_Manager",
    url: fe1024("Ultimate_Football_Manager"),
    cover: fe1024img("Ultimate_Football_Manager.png"),
  },
  {
    title: "Underwater Shoot",
    name: "Underwater Shoot",
    url: fe1024("Underwater Shoot"),
    cover: fe1024img("Underwater Shoot.png"),
  },
  {
    title: "Unlock_The_Lock",
    name: "Unlock_The_Lock",
    url: fe1024("Unlock_The_Lock"),
    cover: fe1024img("Unlock_The_Lock.png"),
  },
  {
    title: "Unruly_Tower",
    name: "Unruly_Tower",
    url: fe1024("Unruly_Tower"),
    cover: fe1024img("Unruly_Tower.png"),
  },
  {
    title: "Unword_it",
    name: "Unword_it",
    url: fe1024("Unword_it"),
    cover: fe1024img("Unword_it.png"),
  },
  {
    title: "Uxu",
    name: "Uxu",
    url: fe1024("Uxu"),
    cover: fe1024img("Uxu.png"),
  },
  {
    title: "Virtual_Pet",
    name: "Virtual_Pet",
    url: fe1024("Virtual_Pet"),
    cover: fe1024img("Virtual_Pet.png"),
  },
  {
    title: "Virtual_Pet_Game",
    name: "Virtual_Pet_Game",
    url: fe1024("Virtual_Pet_Game"),
    cover: fe1024img("Virtual_Pet_Game.png"),
  },
  {
    title: "Virtual_Piano",
    name: "Virtual_Piano",
    url: fe1024("Virtual_Piano"),
    cover: fe1024img("Virtual_Piano.png"),
  },
  {
    title: "Wault_master",
    name: "Wault_master",
    url: fe1024("Wault_master"),
    cover: fe1024img("Wault_master.png"),
  },
  {
    title: "Whack_a_Mole",
    name: "Whack_a_Mole",
    url: fe1024("Whack_a_Mole"),
    cover: fe1024img("Whack_a_Mole.png"),
  },
  {
    title: "Whack_a_Mole_Mario_Version",
    name: "Whack_a_Mole_Mario_Version",
    url: fe1024("Whack_a_Mole_Mario_Version"),
    cover: fe1024img("Whack_a_Mole_Mario_Version.png"),
  },
  {
    title: "Wheel_of_Fortunes",
    name: "Wheel_of_Fortunes",
    url: fe1024("Wheel_of_Fortunes"),
    cover: fe1024img("Wheel_of_Fortunes.png"),
  },
  {
    title: "Wheel_of_fortune",
    name: "Wheel_of_fortune",
    url: fe1024("Wheel_of_fortune"),
    cover: fe1024img("Wheel_of_fortune.png"),
  },
  {
    title: "Which_Color",
    name: "Which_Color",
    url: fe1024("Which_Color"),
    cover: fe1024img("Which_Color.png"),
  },
  {
    title: "Wildcard_Bonanza",
    name: "Wildcard_Bonanza",
    url: fe1024("Wildcard_Bonanza"),
    cover: fe1024img("Wildcard_Bonanza.png"),
  },
  {
    title: "WordChain",
    name: "WordChain",
    url: fe1024("WordChain"),
    cover: fe1024img("WordChain.png"),
  },
  {
    title: "WordSprint",
    name: "WordSprint",
    url: fe1024("WordSprint"),
    cover: fe1024img("WordSprint.png"),
  },
  {
    title: "Word_Association_Game",
    name: "Word_Association_Game",
    url: fe1024("Word_Association_Game"),
    cover: fe1024img("Word_Association_Game.png"),
  },
  {
    title: "Word_Guessing_Game",
    name: "Word_Guessing_Game",
    url: fe1024("Word_Guessing_Game"),
    cover: fe1024img("Word_Guessing_Game.png"),
  },
  {
    title: "Word_Scramble_Game",
    name: "Word_Scramble_Game",
    url: fe1024("Word_Scramble_Game"),
    cover: fe1024img("Word_Scramble_Game.png"),
  },
  {
    title: "Word_Search_Game",
    name: "Word_Search_Game",
    url: fe1024("Word_Search_Game"),
    cover: fe1024img("Word_Search_Game.png"),
  },
  {
    title: "Word_Shuffle_Game",
    name: "Word_Shuffle_Game",
    url: fe1024("Word_Shuffle_Game"),
    cover: fe1024img("Word_Shuffle_Game.png"),
  },
  {
    title: "Word_search_puzzle",
    name: "Word_search_puzzle",
    url: fe1024("Word_search_puzzle"),
    cover: fe1024img("Word_search_puzzle.png"),
  },
  {
    title: "Wordle",
    name: "Wordle",
    url: fe1024("Wordle"),
    cover: fe1024img("Wordle.png"),
  },
  {
    title: "Wordling",
    name: "Wordling",
    url: fe1024("Wordling"),
    cover: fe1024img("Wordling.png"),
  },
  {
    title: "World_Of_Emojis",
    name: "World_Of_Emojis",
    url: fe1024("World_Of_Emojis"),
    cover: fe1024img("World_Of_Emojis.png"),
  },
  {
    title: "Yahtzee",
    name: "Yahtzee",
    url: fe1024("Yahtzee"),
    cover: fe1024img("Yahtzee.png"),
  },
  {
    title: "Zombie_Shooter",
    name: "Zombie_Shooter",
    url: fe1024("Zombie_Shooter"),
    cover: fe1024img("Zombie_Shooter.png"),
  },
  {
    title: "Zurbo",
    name: "Zurbo",
    url: fe1024("Zurbo"),
    cover: fe1024img("Zurbo.png"),
  },
  {
    title: "automated_rock_paper_scissor",
    name: "automated_rock_paper_scissor",
    url: fe1024("automated_rock_paper_scissor"),
    cover: fe1024img("automated_rock_paper_scissor.png"),
  },
  {
    title: "catch_the_falling_stars",
    name: "catch_the_falling_stars",
    url: fe1024("catch_the_falling_stars"),
    cover: fe1024img("catch_the_falling_stars.png"),
  },
  {
    title: "clawCrane",
    name: "clawCrane",
    url: fe1024("clawCrane"),
    cover: fe1024img("clawCrane.png"),
  },
  {
    title: "click_circle",
    name: "click_circle",
    url: fe1024("click_circle"),
    cover: fe1024img("click_circle.png"),
  },
  {
    title: "color matcher",
    name: "color matcher",
    url: fe1024("color matcher"),
    cover: fe1024img("color matcher.png"),
  },
  {
    title: "color_matching_application",
    name: "color_matching_application",
    url: fe1024("color_matching_application"),
    cover: fe1024img("color_matching_application.png"),
  },
  {
    title: "color_switch_challenger",
    name: "color_switch_challenger",
    url: fe1024("color_switch_challenger"),
    cover: fe1024img("color_switch_challenger.png"),
  },
  {
    title: "detona-ralph",
    name: "detona-ralph",
    url: fe1024("detona-ralph"),
    cover: fe1024img("detona-ralph.png"),
  },
  {
    title: "escaperoom",
    name: "escaperoom",
    url: fe1024("escaperoom"),
    cover: fe1024img("escaperoom.png"),
  },
  {
    title: "keySymphony",
    name: "keySymphony",
    url: fe1024("keySymphony"),
    cover: fe1024img("keySymphony.png"),
  },
  {
    title: "linkup",
    name: "linkup",
    url: fe1024("linkup"),
    cover: fe1024img("linkup.png"),
  },
  {
    title: "mario-game",
    name: "mario-game",
    url: fe1024("mario-game"),
    cover: fe1024img("mario-game.png"),
  },
  {
    title: "mario_matching_game",
    name: "mario_matching_game",
    url: fe1024("mario_matching_game"),
    cover: fe1024img("mario_matching_game.png"),
  },
  {
    title: "my_mine_sweeper",
    name: "my_mine_sweeper",
    url: fe1024("my_mine_sweeper"),
    cover: fe1024img("my_mine_sweeper.png"),
  },
  {
    title: "namefate",
    name: "namefate",
    url: fe1024("namefate"),
    cover: fe1024img("namefate.png"),
  },
  {
    title: "numeral-whiz",
    name: "numeral-whiz",
    url: fe1024("numeral-whiz"),
    cover: fe1024img("numeral-whiz.png"),
  },
  {
    title: "oh_flip",
    name: "oh_flip",
    url: fe1024("oh_flip"),
    cover: fe1024img("oh_flip.png"),
  },
  {
    title: "path_finder",
    name: "path_finder",
    url: fe1024("path_finder"),
    cover: fe1024img("path_finder.png"),
  },
  {
    title: "puzzle-game",
    name: "puzzle-game",
    url: fe1024("puzzle-game"),
    cover: fe1024img("puzzle-game.png"),
  },
  {
    title: "quiz_game",
    name: "quiz_game",
    url: fe1024("quiz_game"),
    cover: fe1024img("quiz_game.png"),
  },
  {
    title: "race_car",
    name: "race_car",
    url: fe1024("race_car"),
    cover: fe1024img("race_car.png"),
  },
  {
    title: "rapid_click_frenzy",
    name: "rapid_click_frenzy",
    url: fe1024("rapid_click_frenzy"),
    cover: fe1024img("rapid_click_frenzy.png"),
  },
  {
    title: "reaction_teaser",
    name: "reaction_teaser",
    url: fe1024("reaction_teaser"),
    cover: fe1024img("reaction_teaser.png"),
  },
  {
    title: "road_car",
    name: "road_car",
    url: fe1024("road_car"),
    cover: fe1024img("road_car.png"),
  },
  {
    title: "sand_tetris",
    name: "sand_tetris",
    url: fe1024("sand_tetris"),
    cover: fe1024img("sand_tetris.png"),
  },
  {
    title: "simon says",
    name: "simon says",
    url: fe1024("simon says"),
    cover: fe1024img("simon says.png"),
  },
  {
    title: "snake",
    name: "snake",
    url: fe1024("snake"),
    cover: fe1024img("snake.png"),
  },
  {
    title: "snake_water_gun",
    name: "snake_water_gun",
    url: fe1024("snake_water_gun"),
    cover: fe1024img("snake_water_gun.png"),
  },
  {
    title: "space_drifter",
    name: "space_drifter",
    url: fe1024("space_drifter"),
    cover: fe1024img("space_drifter.png"),
  },
  {
    title: "space_explorer",
    name: "space_explorer",
    url: fe1024("space_explorer"),
    cover: fe1024img("space_explorer.png"),
  },
  {
    title: "test_your_brain",
    name: "test_your_brain",
    url: fe1024("test_your_brain"),
    cover: fe1024img("test_your_brain.png"),
  },
  {
    title: "whack a mole",
    name: "whack a mole",
    url: fe1024("whack a mole"),
    cover: fe1024img("whack a mole.png"),
  },
  {
    title: "witty_word_quest",
    name: "witty_word_quest",
    url: fe1024("witty_word_quest"),
    cover: fe1024img("witty_word_quest.png"),
  },
  {
    title: "wordScramble",
    name: "wordScramble",
    url: fe1024("wordScramble"),
    cover: fe1024img("wordScramble.png"),
  },
  {
    title: "word_association",
    name: "word_association",
    url: fe1024("word_association"),
    cover: fe1024img("word_association.png"),
  },
  {
    title: "word_blitz",
    name: "word_blitz",
    url: fe1024("word_blitz"),
    cover: fe1024img("word_blitz.png"),
  },
];
